SET search_path TO itembaz, public;
DROP TRIGGER sale_source_document_guard ON sales;
DROP FUNCTION protect_sale_source_document();
ALTER TABLE sales DROP COLUMN source_document_id;
DROP TABLE customer_collections;
DROP TABLE supplier_payments;
DROP TABLE supplier_payable_allocations;
DROP FUNCTION validate_supplier_allocation();
DROP TABLE supplier_payable_items;
DROP TABLE supplier_ledger;
DROP TABLE inventory_reservation_ledger;
DROP TABLE operation_document_transitions;
DROP TABLE operation_document_lines;
DROP TABLE operation_documents;
DROP FUNCTION protect_operation_document();
DROP TABLE suppliers;
DROP TABLE procurement_posting_config;
DELETE FROM role_permissions WHERE permission_code IN ('operations.read','sales.orders.manage','purchases.requests.manage','purchases.orders.manage','purchases.receive','purchases.invoices.post','purchases.payments.post','inventory.transfers.manage','inventory.counts.manage','inventory.adjustments.post','customers.collections.post');
DELETE FROM permissions WHERE code IN ('operations.read','sales.orders.manage','purchases.requests.manage','purchases.orders.manage','purchases.receive','purchases.invoices.post','purchases.payments.post','inventory.transfers.manage','inventory.counts.manage','inventory.adjustments.post','customers.collections.post');
