SET search_path TO itembaz, public;
INSERT INTO permissions(code,description) VALUES
 ('inventory.planning.read','View replenishment, lots, expiry, and costing evidence'),
 ('inventory.planning.manage','Create and submit inventory policy revisions'),
 ('inventory.planning.approve','Independently activate or reject inventory policies'),
 ('inventory.lots.manage','Register exact lot allocations before goods receipt posting');

CREATE TABLE inventory_policies(
 id uuid PRIMARY KEY,tenant_id uuid NOT NULL,company_id uuid NOT NULL,branch_id uuid NOT NULL,warehouse_id uuid NOT NULL,product_id uuid NOT NULL,
 status text NOT NULL CHECK(status IN('DRAFT','SUBMITTED','ACTIVE','REJECTED')),cost_method text NOT NULL CHECK(cost_method IN('STANDARD','MOVING_AVERAGE')),lot_controlled boolean NOT NULL,
 reorder_point bigint NOT NULL CHECK(reorder_point>=0),reorder_quantity bigint NOT NULL CHECK(reorder_quantity>0),maximum_stock bigint NOT NULL CHECK(maximum_stock>=reorder_point),safety_stock bigint NOT NULL CHECK(safety_stock BETWEEN 0 AND reorder_point),lead_time_days integer NOT NULL CHECK(lead_time_days BETWEEN 0 AND 3650),preferred_supplier_id uuid,
 reason text NOT NULL CHECK(length(btrim(reason)) BETWEEN 8 AND 500),created_by uuid NOT NULL,created_at timestamptz NOT NULL,approved_by uuid,approved_at timestamptz,
 UNIQUE(tenant_id,company_id,id),FOREIGN KEY(tenant_id,company_id,branch_id,warehouse_id) REFERENCES warehouses(tenant_id,company_id,branch_id,id),FOREIGN KEY(tenant_id,company_id,product_id) REFERENCES products(tenant_id,company_id,id),FOREIGN KEY(tenant_id,company_id,preferred_supplier_id) REFERENCES suppliers(tenant_id,company_id,id),FOREIGN KEY(tenant_id,created_by) REFERENCES users(tenant_id,id),FOREIGN KEY(tenant_id,approved_by) REFERENCES users(tenant_id,id)
);
CREATE UNIQUE INDEX inventory_policy_active ON inventory_policies(tenant_id,company_id,branch_id,warehouse_id,product_id) WHERE status='ACTIVE';
CREATE TABLE inventory_policy_transitions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,company_id uuid NOT NULL,policy_id uuid NOT NULL,from_status text NOT NULL,to_status text NOT NULL,reason text NOT NULL,actor_id uuid NOT NULL,occurred_at timestamptz NOT NULL,FOREIGN KEY(tenant_id,company_id,policy_id) REFERENCES inventory_policies(tenant_id,company_id,id),FOREIGN KEY(tenant_id,actor_id) REFERENCES users(tenant_id,id));

CREATE TABLE inventory_lot_registrations(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,company_id uuid NOT NULL,branch_id uuid NOT NULL,warehouse_id uuid NOT NULL,goods_receipt_id uuid NOT NULL,reason text NOT NULL CHECK(length(btrim(reason)) BETWEEN 8 AND 500),created_by uuid NOT NULL,created_at timestamptz NOT NULL,UNIQUE(tenant_id,company_id,goods_receipt_id),FOREIGN KEY(tenant_id,company_id,goods_receipt_id) REFERENCES operation_documents(tenant_id,company_id,id),FOREIGN KEY(tenant_id,created_by) REFERENCES users(tenant_id,id));
CREATE TABLE inventory_lot_registration_lines(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,company_id uuid NOT NULL,registration_id uuid NOT NULL,product_id uuid NOT NULL,lot_number text NOT NULL,quantity bigint NOT NULL CHECK(quantity>0),manufactured_at timestamptz,expires_at timestamptz,UNIQUE(tenant_id,company_id,registration_id,product_id,lot_number),FOREIGN KEY(tenant_id,company_id,registration_id) REFERENCES inventory_lot_registrations(tenant_id,company_id,id),FOREIGN KEY(tenant_id,company_id,product_id) REFERENCES products(tenant_id,company_id,id),CHECK(expires_at IS NULL OR manufactured_at IS NULL OR expires_at>manufactured_at));
CREATE TABLE inventory_lots(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,company_id uuid NOT NULL,branch_id uuid NOT NULL,warehouse_id uuid NOT NULL,product_id uuid NOT NULL,lot_number text NOT NULL,manufactured_at timestamptz,expires_at timestamptz,created_at timestamptz NOT NULL,UNIQUE(tenant_id,company_id,branch_id,warehouse_id,product_id,lot_number),UNIQUE(tenant_id,company_id,id),FOREIGN KEY(tenant_id,company_id,branch_id,warehouse_id) REFERENCES warehouses(tenant_id,company_id,branch_id,id),FOREIGN KEY(tenant_id,company_id,product_id) REFERENCES products(tenant_id,company_id,id));
CREATE TABLE inventory_lot_ledger(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,company_id uuid NOT NULL,branch_id uuid NOT NULL,warehouse_id uuid NOT NULL,lot_id uuid NOT NULL,product_id uuid NOT NULL,stock_movement_id uuid NOT NULL,source_type text NOT NULL,source_id uuid NOT NULL,quantity bigint NOT NULL CHECK(quantity<>0),occurred_at timestamptz NOT NULL,UNIQUE(tenant_id,company_id,stock_movement_id,lot_id),FOREIGN KEY(tenant_id,company_id,lot_id) REFERENCES inventory_lots(tenant_id,company_id,id),FOREIGN KEY(stock_movement_id) REFERENCES inventory_stock_ledger(id));
CREATE INDEX inventory_lot_expiry_balance ON inventory_lots(tenant_id,company_id,branch_id,warehouse_id,expires_at,product_id);
CREATE TABLE inventory_cost_history(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,company_id uuid NOT NULL,branch_id uuid NOT NULL,warehouse_id uuid NOT NULL,product_id uuid NOT NULL,source_id uuid NOT NULL,cost_method text NOT NULL CHECK(cost_method IN('STANDARD','MOVING_AVERAGE')),quantity_before bigint NOT NULL CHECK(quantity_before>=0),quantity_received bigint NOT NULL CHECK(quantity_received>0),cost_before_minor bigint NOT NULL CHECK(cost_before_minor>=0),receipt_cost_minor bigint NOT NULL CHECK(receipt_cost_minor>=0),cost_after_minor bigint NOT NULL CHECK(cost_after_minor>=0),occurred_at timestamptz NOT NULL,UNIQUE(tenant_id,company_id,source_id,product_id),FOREIGN KEY(tenant_id,company_id,product_id) REFERENCES products(tenant_id,company_id,id));

CREATE FUNCTION protect_inventory_policy() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF TG_OP='DELETE' THEN RAISE EXCEPTION 'inventory policy cannot be deleted' USING ERRCODE='55000';END IF;IF to_jsonb(NEW)-ARRAY['status','approved_by','approved_at']<>to_jsonb(OLD)-ARRAY['status','approved_by','approved_at'] THEN RAISE EXCEPTION 'inventory policy facts are immutable' USING ERRCODE='55000';END IF;RETURN NEW;END $$;
CREATE TRIGGER inventory_policy_guard BEFORE UPDATE OR DELETE ON inventory_policies FOR EACH ROW EXECUTE FUNCTION protect_inventory_policy();
CREATE TRIGGER inventory_policy_transition_guard BEFORE UPDATE OR DELETE ON inventory_policy_transitions FOR EACH ROW EXECUTE FUNCTION reject_mutation();
CREATE TRIGGER inventory_lot_registration_guard BEFORE UPDATE OR DELETE ON inventory_lot_registrations FOR EACH ROW EXECUTE FUNCTION reject_mutation();
CREATE TRIGGER inventory_lot_registration_line_guard BEFORE UPDATE OR DELETE ON inventory_lot_registration_lines FOR EACH ROW EXECUTE FUNCTION reject_mutation();
CREATE TRIGGER inventory_lot_guard BEFORE UPDATE OR DELETE ON inventory_lots FOR EACH ROW EXECUTE FUNCTION reject_mutation();
CREATE TRIGGER inventory_lot_ledger_guard BEFORE UPDATE OR DELETE ON inventory_lot_ledger FOR EACH ROW EXECUTE FUNCTION reject_mutation();
CREATE TRIGGER inventory_cost_history_guard BEFORE UPDATE OR DELETE ON inventory_cost_history FOR EACH ROW EXECUTE FUNCTION reject_mutation();
DO $$ DECLARE n text;BEGIN FOREACH n IN ARRAY ARRAY['inventory_policies','inventory_policy_transitions','inventory_lot_registrations','inventory_lot_registration_lines','inventory_lots','inventory_lot_ledger','inventory_cost_history'] LOOP EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',n);EXECUTE format('CREATE POLICY tenant_isolation ON %I USING (tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid) WITH CHECK (tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',n);END LOOP;END $$;
REVOKE ALL ON inventory_policies,inventory_policy_transitions,inventory_lot_registrations,inventory_lot_registration_lines,inventory_lots,inventory_lot_ledger,inventory_cost_history FROM PUBLIC,itembaz_worker_runtime;
GRANT SELECT,INSERT,UPDATE ON inventory_policies TO itembaz_runtime;
GRANT SELECT,INSERT ON inventory_policy_transitions,inventory_lot_registrations,inventory_lot_registration_lines,inventory_lots,inventory_lot_ledger,inventory_cost_history TO itembaz_runtime;
