SET search_path TO itembaz, public;
INSERT INTO permissions(code,description) VALUES
 ('hr.workforce.read','View shift plans and payroll output evidence'),('hr.shifts.manage','Create and submit shift templates and assignments'),('hr.shifts.approve','Independently activate shifts and approve assignments'),('hr.documents.read','View sensitive employee document metadata'),('hr.documents.manage','Register immutable employee document metadata'),('hr.payroll.export','Generate reproducible payroll payment and statutory output artifacts');
CREATE TABLE shift_templates(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,company_id uuid NOT NULL,code text NOT NULL,name_en text NOT NULL,name_sw text NOT NULL,status text NOT NULL CHECK(status IN('DRAFT','SUBMITTED','ACTIVE','REJECTED')),start_minute integer NOT NULL CHECK(start_minute BETWEEN 0 AND 1439),end_minute integer NOT NULL CHECK(end_minute BETWEEN 0 AND 1439 AND end_minute<>start_minute),break_minutes integer NOT NULL CHECK(break_minutes BETWEEN 0 AND 720),weekday_mask integer NOT NULL CHECK(weekday_mask BETWEEN 1 AND 127),effective_from date NOT NULL,effective_to date,reason text NOT NULL,created_by uuid NOT NULL,created_at timestamptz NOT NULL,approved_by uuid,approved_at timestamptz,UNIQUE(tenant_id,company_id,id),UNIQUE(tenant_id,company_id,code,effective_from),FOREIGN KEY(tenant_id,company_id) REFERENCES legal_companies(tenant_id,id),FOREIGN KEY(tenant_id,created_by) REFERENCES users(tenant_id,id),FOREIGN KEY(tenant_id,approved_by) REFERENCES users(tenant_id,id));
CREATE TABLE shift_assignments(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,company_id uuid NOT NULL,employee_id uuid NOT NULL,shift_template_id uuid NOT NULL,status text NOT NULL CHECK(status IN('DRAFT','SUBMITTED','APPROVED','REJECTED')),starts_on date NOT NULL,ends_on date NOT NULL CHECK(ends_on>=starts_on),reason text NOT NULL,created_by uuid NOT NULL,created_at timestamptz NOT NULL,approved_by uuid,approved_at timestamptz,UNIQUE(tenant_id,company_id,id),FOREIGN KEY(tenant_id,company_id,employee_id) REFERENCES employees(tenant_id,company_id,id),FOREIGN KEY(tenant_id,company_id,shift_template_id) REFERENCES shift_templates(tenant_id,company_id,id),FOREIGN KEY(tenant_id,created_by) REFERENCES users(tenant_id,id),FOREIGN KEY(tenant_id,approved_by) REFERENCES users(tenant_id,id));
CREATE TABLE employee_documents(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,company_id uuid NOT NULL,employee_id uuid NOT NULL,document_type text NOT NULL,title text NOT NULL,object_key text NOT NULL,sha256 char(64) NOT NULL,media_type text NOT NULL,classification text NOT NULL CHECK(classification IN('INTERNAL','CONFIDENTIAL','RESTRICTED')),issued_on date,expires_on date,reason text NOT NULL,created_by uuid NOT NULL,created_at timestamptz NOT NULL,UNIQUE(tenant_id,company_id,id),UNIQUE(tenant_id,company_id,employee_id,sha256),FOREIGN KEY(tenant_id,company_id,employee_id) REFERENCES employees(tenant_id,company_id,id),FOREIGN KEY(tenant_id,created_by) REFERENCES users(tenant_id,id),CHECK(expires_on IS NULL OR issued_on IS NULL OR expires_on>=issued_on));
CREATE TABLE payroll_export_artifacts(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,company_id uuid NOT NULL,payroll_run_id uuid NOT NULL,configuration_id uuid NOT NULL,format text NOT NULL CHECK(format IN('BANK_CSV','STATUTORY_CSV')),file_name text NOT NULL,media_type text NOT NULL,sha256 char(64) NOT NULL,configuration_sha256 char(64) NOT NULL,row_count bigint NOT NULL CHECK(row_count>0),content text NOT NULL,created_by uuid NOT NULL,created_at timestamptz NOT NULL,UNIQUE(tenant_id,company_id,id),UNIQUE(tenant_id,company_id,payroll_run_id,configuration_id,format),FOREIGN KEY(tenant_id,company_id,payroll_run_id) REFERENCES payroll_runs(tenant_id,company_id,id),FOREIGN KEY(tenant_id,company_id,configuration_id) REFERENCES configuration_versions(tenant_id,company_id,id),FOREIGN KEY(tenant_id,created_by) REFERENCES users(tenant_id,id));
CREATE TABLE workforce_transitions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,company_id uuid NOT NULL,entity_type text NOT NULL CHECK(entity_type IN('SHIFT_TEMPLATE','SHIFT_ASSIGNMENT')),entity_id uuid NOT NULL,from_status text NOT NULL,to_status text NOT NULL,reason text NOT NULL,actor_id uuid NOT NULL,occurred_at timestamptz NOT NULL,FOREIGN KEY(tenant_id,actor_id) REFERENCES users(tenant_id,id));
CREATE INDEX shift_assignment_calendar ON shift_assignments(tenant_id,company_id,employee_id,starts_on,ends_on,status);CREATE INDEX employee_document_expiry ON employee_documents(tenant_id,company_id,expires_on,employee_id);
CREATE FUNCTION protect_workforce_status() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN IF TG_OP='DELETE' THEN RAISE EXCEPTION 'workforce record cannot be deleted' USING ERRCODE='55000';END IF;IF to_jsonb(NEW)-ARRAY['status','approved_by','approved_at']<>to_jsonb(OLD)-ARRAY['status','approved_by','approved_at'] THEN RAISE EXCEPTION 'workforce facts are immutable' USING ERRCODE='55000';END IF;RETURN NEW;END$$;
CREATE TRIGGER shift_template_guard BEFORE UPDATE OR DELETE ON shift_templates FOR EACH ROW EXECUTE FUNCTION protect_workforce_status();CREATE TRIGGER shift_assignment_guard BEFORE UPDATE OR DELETE ON shift_assignments FOR EACH ROW EXECUTE FUNCTION protect_workforce_status();CREATE TRIGGER employee_document_guard BEFORE UPDATE OR DELETE ON employee_documents FOR EACH ROW EXECUTE FUNCTION reject_mutation();CREATE TRIGGER payroll_export_guard BEFORE UPDATE OR DELETE ON payroll_export_artifacts FOR EACH ROW EXECUTE FUNCTION reject_mutation();CREATE TRIGGER workforce_transition_guard BEFORE UPDATE OR DELETE ON workforce_transitions FOR EACH ROW EXECUTE FUNCTION reject_mutation();
DO $$DECLARE n text;BEGIN FOREACH n IN ARRAY ARRAY['shift_templates','shift_assignments','employee_documents','payroll_export_artifacts','workforce_transitions'] LOOP EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',n);EXECUTE format('CREATE POLICY tenant_isolation ON %I USING (tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid) WITH CHECK (tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',n);END LOOP;END$$;
REVOKE ALL ON shift_templates,shift_assignments,employee_documents,payroll_export_artifacts,workforce_transitions FROM PUBLIC,itembaz_worker_runtime;GRANT SELECT,INSERT,UPDATE ON shift_templates,shift_assignments TO itembaz_runtime;GRANT SELECT,INSERT ON employee_documents,payroll_export_artifacts,workforce_transitions TO itembaz_runtime;
