SET search_path TO itembaz, public;
INSERT INTO permissions(code,description) VALUES
 ('hr.people.read','View employees, attendance, leave, loans, payroll and payslips'),('hr.employees.manage','Manage employee master records'),
 ('hr.attendance.manage','Record and reverse attendance ledger entries'),('hr.leave.manage','Create and submit leave requests'),
 ('hr.leave.approve','Independently approve or reject leave'),('hr.settings.manage','Manage effective-dated HR configuration'),
 ('hr.loans.manage','Create and submit employee loans'),('hr.loans.approve','Independently approve and post employee loans'),
 ('hr.payroll.manage','Create and submit payroll runs'),('hr.payroll.approve','Independently approve and post payroll runs');

CREATE TABLE employees(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,company_id uuid NOT NULL,branch_id uuid,warehouse_id uuid,employee_number text NOT NULL,full_name text NOT NULL,job_title text NOT NULL DEFAULT '',department text NOT NULL DEFAULT '',hire_date date NOT NULL,status text NOT NULL CHECK(status IN('ACTIVE','INACTIVE')),currency char(3) NOT NULL,base_salary_minor bigint NOT NULL CHECK(base_salary_minor>=0),created_by uuid NOT NULL,created_at timestamptz NOT NULL,UNIQUE(tenant_id,company_id,id),UNIQUE(tenant_id,company_id,employee_number),FOREIGN KEY(tenant_id,company_id) REFERENCES legal_companies(tenant_id,id),FOREIGN KEY(tenant_id,created_by) REFERENCES users(tenant_id,id));
CREATE TABLE attendance_entries(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,company_id uuid NOT NULL,employee_id uuid NOT NULL,work_date date NOT NULL,regular_minutes bigint NOT NULL CHECK(regular_minutes BETWEEN -1440 AND 1440),overtime_minutes bigint NOT NULL CHECK(overtime_minutes BETWEEN -720 AND 720),reason text NOT NULL,reversal_of uuid,recorded_by uuid NOT NULL,recorded_at timestamptz NOT NULL,UNIQUE(tenant_id,company_id,id),UNIQUE(tenant_id,company_id,reversal_of),FOREIGN KEY(tenant_id,company_id,employee_id) REFERENCES employees(tenant_id,company_id,id),FOREIGN KEY(reversal_of) REFERENCES attendance_entries(id),FOREIGN KEY(tenant_id,recorded_by) REFERENCES users(tenant_id,id));
CREATE TABLE leave_types(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,company_id uuid NOT NULL,code text NOT NULL,name_en text NOT NULL,name_sw text NOT NULL,annual_entitlement_days bigint NOT NULL CHECK(annual_entitlement_days BETWEEN 0 AND 366),effective_from date NOT NULL,effective_to date,created_by uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,company_id,id),UNIQUE(tenant_id,company_id,code,effective_from),FOREIGN KEY(tenant_id,company_id) REFERENCES legal_companies(tenant_id,id),FOREIGN KEY(tenant_id,created_by) REFERENCES users(tenant_id,id));
CREATE TABLE leave_requests(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,company_id uuid NOT NULL,employee_id uuid NOT NULL,leave_type_id uuid NOT NULL,starts_on date NOT NULL,ends_on date NOT NULL CHECK(ends_on>=starts_on),days bigint NOT NULL CHECK(days>0),reason text NOT NULL,status text NOT NULL CHECK(status IN('DRAFT','SUBMITTED','APPROVED','REJECTED')),created_by uuid NOT NULL,created_at timestamptz NOT NULL,approved_by uuid,approved_at timestamptz,UNIQUE(tenant_id,company_id,id),FOREIGN KEY(tenant_id,company_id,employee_id) REFERENCES employees(tenant_id,company_id,id),FOREIGN KEY(tenant_id,company_id,leave_type_id) REFERENCES leave_types(tenant_id,company_id,id),FOREIGN KEY(tenant_id,created_by) REFERENCES users(tenant_id,id),FOREIGN KEY(tenant_id,approved_by) REFERENCES users(tenant_id,id));
CREATE TABLE employee_loans(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,company_id uuid NOT NULL,employee_id uuid NOT NULL,reference text NOT NULL,currency char(3) NOT NULL,principal_minor bigint NOT NULL CHECK(principal_minor>0),outstanding_minor bigint NOT NULL CHECK(outstanding_minor>=0),receivable_account_id text NOT NULL,bank_account_id text NOT NULL,reason text NOT NULL,status text NOT NULL CHECK(status IN('DRAFT','SUBMITTED','APPROVED','POSTED','REJECTED')),created_by uuid NOT NULL,created_at timestamptz NOT NULL,approved_by uuid,journal_id uuid,UNIQUE(tenant_id,company_id,id),UNIQUE(tenant_id,company_id,reference),FOREIGN KEY(tenant_id,company_id,employee_id) REFERENCES employees(tenant_id,company_id,id),FOREIGN KEY(tenant_id,company_id,receivable_account_id) REFERENCES gl_accounts(tenant_id,company_id,id),FOREIGN KEY(tenant_id,company_id,bank_account_id) REFERENCES gl_accounts(tenant_id,company_id,id),FOREIGN KEY(tenant_id,created_by) REFERENCES users(tenant_id,id),FOREIGN KEY(tenant_id,approved_by) REFERENCES users(tenant_id,id),FOREIGN KEY(journal_id) REFERENCES journals(id));
CREATE TABLE payroll_runs(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,company_id uuid NOT NULL,reference text NOT NULL,currency char(3) NOT NULL,period_start date NOT NULL,period_end date NOT NULL CHECK(period_end>=period_start),payment_date date NOT NULL,status text NOT NULL CHECK(status IN('DRAFT','SUBMITTED','APPROVED','POSTED','REJECTED')),salary_expense_account_id text NOT NULL,payroll_payable_account_id text NOT NULL,deduction_liability_account_id text NOT NULL,reason text NOT NULL,gross_minor bigint NOT NULL,deductions_minor bigint NOT NULL,net_minor bigint NOT NULL,created_by uuid NOT NULL,created_at timestamptz NOT NULL,approved_by uuid,journal_id uuid,UNIQUE(tenant_id,company_id,id),UNIQUE(tenant_id,company_id,reference),FOREIGN KEY(tenant_id,company_id) REFERENCES legal_companies(tenant_id,id),FOREIGN KEY(tenant_id,company_id,salary_expense_account_id) REFERENCES gl_accounts(tenant_id,company_id,id),FOREIGN KEY(tenant_id,company_id,payroll_payable_account_id) REFERENCES gl_accounts(tenant_id,company_id,id),FOREIGN KEY(tenant_id,company_id,deduction_liability_account_id) REFERENCES gl_accounts(tenant_id,company_id,id),FOREIGN KEY(tenant_id,created_by) REFERENCES users(tenant_id,id),FOREIGN KEY(tenant_id,approved_by) REFERENCES users(tenant_id,id),FOREIGN KEY(journal_id) REFERENCES journals(id));
CREATE TABLE payroll_lines(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,company_id uuid NOT NULL,payroll_run_id uuid NOT NULL,employee_id uuid NOT NULL,gross_minor bigint NOT NULL,other_deductions_minor bigint NOT NULL,loan_deduction_minor bigint NOT NULL,net_minor bigint NOT NULL,UNIQUE(tenant_id,company_id,payroll_run_id,employee_id),FOREIGN KEY(tenant_id,company_id,payroll_run_id) REFERENCES payroll_runs(tenant_id,company_id,id),FOREIGN KEY(tenant_id,company_id,employee_id) REFERENCES employees(tenant_id,company_id,id));
CREATE TABLE people_transitions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,company_id uuid NOT NULL,entity_type text NOT NULL,entity_id uuid NOT NULL,from_status text NOT NULL,to_status text NOT NULL,reason text NOT NULL,actor_id uuid NOT NULL,occurred_at timestamptz NOT NULL,FOREIGN KEY(tenant_id,actor_id) REFERENCES users(tenant_id,id));
CREATE INDEX employee_scope_list ON employees(tenant_id,company_id,status,employee_number); CREATE INDEX attendance_employee_date ON attendance_entries(tenant_id,company_id,employee_id,work_date); CREATE INDEX leave_employee_date ON leave_requests(tenant_id,company_id,employee_id,starts_on,ends_on); CREATE INDEX payroll_period ON payroll_runs(tenant_id,company_id,period_end,status);
CREATE FUNCTION protect_people_master() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF TG_OP='DELETE' THEN RAISE EXCEPTION 'people record cannot be deleted' USING ERRCODE='55000'; END IF; RETURN NEW; END $$;
CREATE TRIGGER employees_guard BEFORE DELETE ON employees FOR EACH ROW EXECUTE FUNCTION protect_people_master(); CREATE TRIGGER attendance_guard BEFORE UPDATE OR DELETE ON attendance_entries FOR EACH ROW EXECUTE FUNCTION reject_mutation(); CREATE TRIGGER leave_types_guard BEFORE UPDATE OR DELETE ON leave_types FOR EACH ROW EXECUTE FUNCTION reject_mutation(); CREATE TRIGGER payroll_lines_guard BEFORE UPDATE OR DELETE ON payroll_lines FOR EACH ROW EXECUTE FUNCTION reject_mutation(); CREATE TRIGGER people_transitions_guard BEFORE UPDATE OR DELETE ON people_transitions FOR EACH ROW EXECUTE FUNCTION reject_mutation();
DO $$ DECLARE n text; BEGIN FOREACH n IN ARRAY ARRAY['employees','attendance_entries','leave_types','leave_requests','employee_loans','payroll_runs','payroll_lines','people_transitions'] LOOP EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',n); EXECUTE format('CREATE POLICY tenant_isolation ON %I USING (tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid) WITH CHECK (tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',n); END LOOP; END $$;
REVOKE ALL ON employees,attendance_entries,leave_types,leave_requests,employee_loans,payroll_runs,payroll_lines,people_transitions FROM PUBLIC,itembaz_worker_runtime; GRANT SELECT,INSERT,UPDATE ON employees,leave_requests,employee_loans,payroll_runs TO itembaz_runtime; GRANT SELECT,INSERT ON attendance_entries,leave_types,payroll_lines,people_transitions TO itembaz_runtime;
