"use client";

import { useState } from "react";
import { useLanguage } from "@/components/language-provider";
import { text } from "@/lib/i18n";
import { formatMinorUnits } from "@/live-api/format";
import type { CreateIntercompanyCommand, GroupFinanceWorkspace, IntercompanyTransaction, IntercompanyTransitionCommand, PublicProblem } from "@/live-api/types";

type Action={action:"create"|"transition";id?:string;command:unknown};
async function send(body:Action){const response=await fetch("/api/live/finance/group",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify(body)});const value:unknown=await response.json();if(!response.ok)throw value;return value as IntercompanyTransaction;}
function asProblem(value:unknown):PublicProblem{return value&&typeof value==="object"&&"detail" in value?value as PublicProblem:{type:"about:blank",title:"Failed",status:500,code:"group_finance_failed",detail:value instanceof Error?value.message:"The group finance command failed."};}

export function GroupFinance({workspace}:{workspace:GroupFinanceWorkspace}){
  const {l,locale}=useLanguage();const [transactions,setTransactions]=useState(workspace.transactions);const [busy,setBusy]=useState(false);const [failure,setFailure]=useState<PublicProblem|null>(null);const permissions=new Set(workspace.context.permissions);const money=(value:number)=>formatMinorUnits(value,workspace.context.currency,locale);
  async function run(body:Action){setBusy(true);setFailure(null);try{const value=await send(body);setTransactions((current)=>current.some((item)=>item.id===value.id)?current.map((item)=>item.id===value.id?value:item):[value,...current]);}catch(error){setFailure(asProblem(error));}finally{setBusy(false);}}
  async function transition(item:IntercompanyTransaction,status:IntercompanyTransitionCommand["status"]){await run({action:"transition",id:item.id,command:{status,reason:`${status} after dual-company intercompany evidence review`}});}
  return <section className="page-stack"><header className="module-header"><div><p className="eyebrow">{l(text("Separate books, one group", "Vitabu tofauti, kundi moja"))}</p><h1>{l(text("Intercompany and consolidation", "Miamala baina ya kampuni na ujumuishaji"))}</h1><p>{l(text("Dual-company approval, paired journals, and explicit group eliminations.","Idhini za kampuni mbili, majarida yaliyooanishwa na uondoaji wa kundi ulio wazi."))}</p></div></header>
    {failure?<div className="problem-banner" role="alert"><strong>{failure.code}</strong><span>{failure.detail}</span></div>:null}
    {workspace.consolidation?<ConsolidationSummary workspace={workspace} money={money}/>:null}
    <section className="card"><div className="card-heading"><div><h2>{l(text("Intercompany queue","Foleni ya baina ya kampuni"))}</h2></div></div>
      {permissions.has("finance.intercompany.manage")?<IntercompanyForm disabled={busy} workspace={workspace} onCreate={(command)=>run({action:"create",command})}/>:null}
      <div className="table-scroll"><table><thead><tr><th>{l(text("Reference","Rejea"))}</th><th>{l(text("Counterparty","Kampuni nyingine"))}</th><th>{l(text("Type","Aina"))}</th><th>{l(text("Amount","Kiasi"))}</th><th>{l(text("Status","Hali"))}</th><th>{l(text("Actions","Vitendo"))}</th></tr></thead><tbody>{transactions.map((item)=>{const source=item.scope.company_id===workspace.context.company_id;const counter=item.counterparty_company_id===workspace.context.company_id;return <tr key={item.id}><td><strong>{item.reference}</strong><br/><small>{item.reason}</small></td><td>{item.counterparty_company_name||item.counterparty_company_id}</td><td>{item.type}</td><td>{money(item.amount_minor)}</td><td>{item.status}</td><td><div className="action-row">
        {source&&item.status==="DRAFT"&&permissions.has("finance.intercompany.manage")?<button className="button button-secondary" disabled={busy} onClick={()=>transition(item,"SUBMITTED")}>{l(text("Submit","Wasilisha"))}</button>:null}
        {source&&item.status==="SUBMITTED"&&permissions.has("finance.intercompany.approve")?<><button className="button button-primary" disabled={busy} onClick={()=>transition(item,"SOURCE_APPROVED")}>{l(text("Source approve","Idhini ya chanzo"))}</button><button className="button button-secondary" disabled={busy} onClick={()=>transition(item,"REJECTED")}>{l(text("Reject","Kataa"))}</button></>:null}
        {counter&&item.status==="SOURCE_APPROVED"&&permissions.has("finance.intercompany.approve")?<><button className="button button-primary" disabled={busy} onClick={()=>transition(item,"POSTED")}>{l(text("Confirm and post","Thibitisha na weka"))}</button><button className="button button-secondary" disabled={busy} onClick={()=>transition(item,"REJECTED")}>{l(text("Reject","Kataa"))}</button></>:null}
      </div></td></tr>;})}</tbody></table></div>
    </section></section>;
}

function ConsolidationSummary({workspace,money}:{workspace:GroupFinanceWorkspace;money:(value:number)=>string}){const {l}=useLanguage();const report=workspace.consolidation;if(!report)return null;return <section className="card"><div className="card-heading"><div><h2>{l(text("Group consolidation","Ujumuishaji wa kundi"))}</h2><p>{report.companies.length} {l(text("legal companies","kampuni za kisheria"))}</p></div><span className={`status-pill ${report.balanced?"status-posted":"status-rejected"}`}>{report.balanced?l(text("Balanced","Imesawazika")):l(text("Review required","Ukaguzi unahitajika"))}</span></div><div className="metric-grid"><article><span>{l(text("Assets after elimination","Mali baada ya uondoaji"))}</span><strong>{money(report.assets_minor)}</strong></article><article><span>{l(text("Liabilities after elimination","Madeni baada ya uondoaji"))}</span><strong>{money(report.liabilities_minor)}</strong></article><article><span>{l(text("Net profit","Faida halisi"))}</span><strong>{money(report.net_profit_minor)}</strong></article><article><span>{l(text("Balance eliminations","Uondoaji wa salio"))}</span><strong>{money(report.intercompany_balance_elimination_minor)}</strong></article><article><span>{l(text("Activity eliminations","Uondoaji wa shughuli"))}</span><strong>{money(report.intercompany_activity_elimination_minor)}</strong></article></div></section>;}

function IntercompanyForm({disabled,workspace,onCreate}:{disabled:boolean;workspace:GroupFinanceWorkspace;onCreate:(command:CreateIntercompanyCommand)=>void}){const {l}=useLanguage();const [kind,setKind]=useState<CreateIntercompanyCommand["type"]>("COST_ALLOCATION");const accounts=(type:string)=>workspace.accounts.filter((account)=>account.type===type);const companies=workspace.consolidation?.companies.filter((company)=>company.company_id!==workspace.context.company_id)??[];return <form className="bank-import-form" onSubmit={(event)=>{event.preventDefault();const f=new FormData(event.currentTarget);onCreate({counterparty_company_id:String(f.get("company")),reference:String(f.get("reference")),type:kind,currency:workspace.context.currency,amount_minor:Math.round(Number(f.get("amount"))*100),occurred_at:new Date(String(f.get("date"))+"T12:00:00Z").toISOString(),source_debit_account_id:String(f.get("source_debit")),source_credit_account_id:String(f.get("source_credit")),counterparty_debit_account_id:String(f.get("counter_debit")),counterparty_credit_account_id:String(f.get("counter_credit")),reason:String(f.get("reason"))});}}>
    <label>{l(text("Counterparty company UUID","UUID ya kampuni nyingine"))}<input name="company" list="group-companies" required/><datalist id="group-companies">{companies.map((company)=><option key={company.company_id} value={company.company_id}>{company.company_name}</option>)}</datalist></label><label>{l(text("Reference","Rejea"))}<input name="reference" minLength={2} required/></label><label>{l(text("Transaction type","Aina ya muamala"))}<select value={kind} onChange={(event)=>setKind(event.target.value as CreateIntercompanyCommand["type"])}><option value="COST_ALLOCATION">{l(text("Cost allocation","Ugawaji wa gharama"))}</option><option value="CASH_TRANSFER">{l(text("Cash transfer","Uhamisho wa fedha"))}</option></select></label><label>{l(text("Amount TZS","Kiasi TZS"))}<input name="amount" type="number" min="0.01" step="0.01" required/></label><label>{l(text("Accounting date","Tarehe ya uhasibu"))}<input name="date" type="date" required/></label>
    <AccountSelect name="source_debit" label={l(text("Source intercompany receivable","Dai la baina ya kampuni"))} accounts={accounts("ASSET")}/><AccountSelect name="source_credit" label={l(text(kind==="COST_ALLOCATION"?"Source recovery income":"Source bank account",kind==="COST_ALLOCATION"?"Mapato ya urejeshaji":"Akaunti ya benki ya chanzo"))} accounts={accounts(kind==="COST_ALLOCATION"?"REVENUE":"ASSET")}/><label>{l(text("Counterparty debit account ID","Akaunti ya debiti ya kampuni nyingine"))}<input name="counter_debit" required/></label><label>{l(text("Counterparty payable account ID","Akaunti ya deni ya kampuni nyingine"))}<input name="counter_credit" required/></label><label>{l(text("Reason","Sababu"))}<input name="reason" minLength={8} required/></label><button className="button button-primary" disabled={disabled}>{l(text("Create intercompany draft","Unda rasimu ya baina ya kampuni"))}</button>
  </form>;}
function AccountSelect({name,label,accounts}:{name:string;label:string;accounts:GroupFinanceWorkspace["accounts"]}){return <label>{label}<select name={name} required>{accounts.map((account)=><option key={account.id} value={account.id}>{account.code} · {account.name}</option>)}</select></label>;}
