"use client";

import { useState } from "react";
import { useLanguage } from "@/components/language-provider";
import { text } from "@/lib/i18n";
import { formatMinorUnits } from "@/live-api/format";
import type { CreateTreasuryFacilityCommand, PostTreasuryTransactionCommand, PublicProblem, TreasuryFacility, TreasuryWorkspace } from "@/live-api/types";

type Action = { action: string; id?: string; command: unknown };
function problem(value: unknown): PublicProblem { return value && typeof value === "object" && "detail" in value ? value as PublicProblem : { type: "about:blank", title: "Failed", status: 500, code: "treasury_failed", detail: value instanceof Error ? value.message : "The treasury command failed." }; }
async function send(body: Action): Promise<TreasuryFacility> {
  const response = await fetch("/api/live/finance/treasury", { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify(body) });
  const value: unknown = await response.json(); if (!response.ok) throw value; return value as TreasuryFacility;
}

export function TreasuryWorkbench({ workspace }: { workspace: TreasuryWorkspace }) {
  const { l, locale } = useLanguage(); const [facilities, setFacilities] = useState(workspace.facilities); const [busy, setBusy] = useState(false); const [failure, setFailure] = useState<PublicProblem | null>(null);
  const permissions = new Set(workspace.context.permissions); const money = (value: number) => formatMinorUnits(value, workspace.context.currency, locale);
  async function run(body: Action) { setBusy(true); setFailure(null); try { const value = await send(body); setFacilities((current) => current.some((item) => item.id === value.id) ? current.map((item) => item.id === value.id ? value : item) : [value, ...current]); } catch (error) { setFailure(problem(error)); } finally { setBusy(false); } }
  return <section className="page-stack">
    <header className="module-header"><div><p className="eyebrow">{l(text("Fund and reconcile", "Fadhili na linganisha"))}</p><h1>{l(text("Treasury facilities", "Mikopo na hazina"))}</h1><p>{l(text("Govern borrowing limits, approvals, interest, repayments, and their ledger evidence.", "Dhibiti mipaka ya mikopo, idhini, riba, marejesho na ushahidi wake wa leja."))}</p></div></header>
    {failure ? <div className="problem-banner" role="alert"><strong>{failure.code}</strong><span>{failure.detail}</span></div> : null}
    <section className="card"><div className="card-heading"><div><h2>{l(text("Facility register", "Daftari la mikopo"))}</h2></div></div>
      {permissions.has("finance.treasury.manage") ? <FacilityForm disabled={busy} accounts={workspace.accounts} onCreate={(command) => run({ action: "create_facility", command })} /> : null}
      <div className="table-scroll"><table><thead><tr><th>{l(text("Facility", "Mkopo"))}</th><th>{l(text("Status", "Hali"))}</th><th>{l(text("Limit", "Kikomo"))}</th><th>{l(text("Principal", "Mtaji"))}</th><th>{l(text("Interest due", "Riba inayodaiwa"))}</th><th>{l(text("Actions", "Vitendo"))}</th></tr></thead><tbody>
        {facilities.map((facility) => <tr key={facility.id}><td><strong>{facility.reference}</strong><br />{facility.lender} · {facility.type === "TERM_LOAN" ? l(text("Term loan", "Mkopo wa muda")) : l(text("Overdraft", "Salio hasi"))}<br /><small>{facility.transactions.length} {l(text("postings", "miamala"))}</small></td><td>{facility.status}</td><td>{money(facility.limit_minor)}</td><td>{money(facility.outstanding_principal_minor)}</td><td>{money(facility.accrued_interest_minor)}</td><td><div className="action-row">
          {facility.status === "DRAFT" && permissions.has("finance.treasury.manage") ? <button className="button button-secondary" disabled={busy} onClick={() => run({ action: "transition_facility", id: facility.id, command: { status: "SUBMITTED", reason: "Facility evidence submitted for independent review" } })}>{l(text("Submit", "Wasilisha"))}</button> : null}
          {facility.status === "SUBMITTED" && permissions.has("finance.treasury.approve") ? <><button className="button button-primary" disabled={busy} onClick={() => run({ action: "transition_facility", id: facility.id, command: { status: "ACTIVE", reason: "Independent treasury facility approval complete" } })}>{l(text("Approve", "Idhinisha"))}</button><button className="button button-secondary" disabled={busy} onClick={() => run({ action: "transition_facility", id: facility.id, command: { status: "REJECTED", reason: "Facility rejected after independent evidence review" } })}>{l(text("Reject", "Kataa"))}</button></> : null}
          {facility.status === "ACTIVE" && permissions.has("finance.treasury.transact") ? <TransactionForm disabled={busy} onPost={(command) => run({ action: "post_transaction", id: facility.id, command })} /> : null}
          {facility.status === "ACTIVE" && facility.outstanding_principal_minor === 0 && facility.accrued_interest_minor === 0 && permissions.has("finance.treasury.approve") ? <button className="button button-secondary" disabled={busy} onClick={() => run({ action: "transition_facility", id: facility.id, command: { status: "CLOSED", reason: "Facility fully settled and reconciled for closure" } })}>{l(text("Close", "Funga"))}</button> : null}
        </div></td></tr>)}
      </tbody></table></div>
    </section>
  </section>;
}

function FacilityForm({ disabled, accounts, onCreate }: { disabled: boolean; accounts: TreasuryWorkspace["accounts"]; onCreate: (command: CreateTreasuryFacilityCommand) => void }) {
  const { l } = useLanguage(); const choices = (kind: string) => accounts.filter((account) => account.type === kind);
  return <form className="bank-import-form" onSubmit={(event) => { event.preventDefault(); const f = new FormData(event.currentTarget); onCreate({ reference: String(f.get("reference")), lender: String(f.get("lender")), type: String(f.get("type")) as CreateTreasuryFacilityCommand["type"], currency: "TZS", limit_minor: Math.round(Number(f.get("limit")) * 100), annual_interest_basis_points: Math.round(Number(f.get("rate")) * 100), start_date: String(f.get("start")), maturity_date: String(f.get("maturity")), bank_account_id: String(f.get("bank")), principal_account_id: String(f.get("principal")), interest_expense_account_id: String(f.get("expense")), accrued_interest_account_id: String(f.get("accrued")), reason: String(f.get("reason")) }); }}>
    <label>{l(text("Reference", "Rejea"))}<input name="reference" required minLength={2} /></label><label>{l(text("Lender", "Mkopeshaji"))}<input name="lender" required minLength={3} /></label><label>{l(text("Type", "Aina"))}<select name="type"><option value="TERM_LOAN">{l(text("Term loan", "Mkopo wa muda"))}</option><option value="OVERDRAFT">{l(text("Overdraft", "Salio hasi"))}</option></select></label><label>{l(text("Limit TZS", "Kikomo TZS"))}<input name="limit" type="number" min="0.01" step="0.01" required /></label><label>{l(text("Annual rate %", "Riba ya mwaka %"))}<input name="rate" type="number" min="0" max="1000" step="0.01" required /></label><label>{l(text("Start date", "Tarehe ya kuanza"))}<input name="start" type="date" required /></label><label>{l(text("Maturity", "Mwisho"))}<input name="maturity" type="date" required /></label>
    <AccountSelect name="bank" label={l(text("Bank account", "Akaunti ya benki"))} accounts={choices("ASSET")} /><AccountSelect name="principal" label={l(text("Principal liability", "Deni la mtaji"))} accounts={choices("LIABILITY")} /><AccountSelect name="expense" label={l(text("Interest expense", "Gharama ya riba"))} accounts={choices("EXPENSE")} /><AccountSelect name="accrued" label={l(text("Accrued interest", "Riba iliyokusanywa"))} accounts={choices("LIABILITY")} /><label>{l(text("Reason", "Sababu"))}<input name="reason" required minLength={8} /></label><button className="button button-primary" disabled={disabled}>{l(text("Create facility", "Unda mkopo"))}</button>
  </form>;
}
function AccountSelect({ name, label, accounts }: { name: string; label: string; accounts: TreasuryWorkspace["accounts"] }) { return <label>{label}<select name={name} required>{accounts.map((account) => <option key={account.id} value={account.id}>{account.code} · {account.name}</option>)}</select></label>; }
function TransactionForm({ disabled, onPost }: { disabled: boolean; onPost: (command: PostTreasuryTransactionCommand) => void }) { const { l } = useLanguage(); return <form className="action-row" onSubmit={(event) => { event.preventDefault(); const f = new FormData(event.currentTarget); onPost({ type: String(f.get("type")) as PostTreasuryTransactionCommand["type"], amount_minor: Math.round(Number(f.get("amount")) * 100), occurred_at: new Date(String(f.get("date")) + "T12:00:00Z").toISOString(), reason: "Approved treasury transaction posting evidence" }); }}><select aria-label={l(text("Transaction type", "Aina ya muamala"))} name="type"><option value="DRAWDOWN">{l(text("Drawdown", "Toa mkopo"))}</option><option value="INTEREST_ACCRUAL">{l(text("Accrue interest", "Kusanya riba"))}</option><option value="PRINCIPAL_REPAYMENT">{l(text("Repay principal", "Rejesha mtaji"))}</option><option value="INTEREST_PAYMENT">{l(text("Pay interest", "Lipa riba"))}</option></select><input aria-label={l(text("Amount TZS", "Kiasi TZS"))} name="amount" type="number" min="0.01" step="0.01" required /><input aria-label={l(text("Posting date", "Tarehe ya muamala"))} name="date" type="date" required /><button className="button button-primary" disabled={disabled}>{l(text("Post", "Weka"))}</button></form>; }
