import type { Locale } from "@/domain/erp";

const catalog = {
  en: {
    sales: "Sales",
    overview: "Overview",
    transactions: "Transactions",
    quotesOrders: "Quotes & orders",
    payments: "Payments",
    returns: "Returns",
    homeIntro: "Create sales, handle customer payments, and resolve the work that needs attention.",
    newSale: "New sale",
    newQuote: "New quote",
    recordPayment: "Record payment",
    processReturn: "Process return",
    viewTransactions: "View transactions",
    quickActions: "Quick actions",
    startQuoteDetail: "Prepare a customer quotation",
    paymentDetail: "Allocate a customer payment",
    returnDetail: "Find the original sale and start a correction",
    transactionDetail: "Search and review posted sales",
    needsAttention: "Needs your attention",
    readyToFulfil: "Ready to fulfil",
    readyToFulfilDetail: "Approved customer orders can now be completed.",
    exceptions: "Exceptions",
    exceptionsDetail: "Unresolved fiscal states and reversed sales need review.",
    submittedDocuments: "Submitted documents",
    submittedDocumentsDetail: "Sales documents are waiting for a decision.",
    caughtUp: "You’re caught up",
    caughtUpDetail: "There are no sales exceptions or ready orders in this working scope.",
    recentTransactions: "Recent transactions",
    recentTransactionsDetail: "The latest posted sales in this working scope.",
    viewAll: "View all",
    type: "Type",
    number: "Number",
    customer: "Customer",
    amount: "Amount",
    status: "Status",
    date: "Date",
    sale: "Sale",
    reversal: "Reversal",
    cash: "Cash",
    credit: "Credit",
    posted: "Posted",
    reversed: "Reversed",
    fiscalPending: "Fiscal pending",
    fiscalFailed: "Fiscal failed",
    fiscalNotConfigured: "Fiscal not configured",
    openTransaction: "Open transaction",
    noTransactions: "No sales have been posted in this scope yet.",
    completeFirstSale: "Complete the first sale",
    searchTransactions: "Search transactions",
    searchPlaceholder: "Search receipt or customer…",
    clearSearch: "Clear search",
    noMatches: "No transactions match this search.",
    allStatuses: "All statuses",
    postedOnly: "Posted",
    reversedOnly: "Reversed",
    exceptionsOnly: "Exceptions",
    results: "results",
    previousPage: "Previous page",
    nextPage: "Next page",
    transactionRegister: "Transaction register",
    transactionRegisterIntro: "Search posted sales and open the original business record.",
    returnsRegister: "Returns & corrections",
    returnsRegisterIntro: "Find the original posted sale and begin an authorized correction.",
    eligibleSales: "Sales eligible for correction",
    returnHint: "Choose the original sale you need to correct. The posted record will remain unchanged.",
  },
  sw: {
    sales: "Mauzo",
    overview: "Muhtasari",
    transactions: "Miamala",
    quotesOrders: "Nukuu na oda",
    payments: "Malipo",
    returns: "Marejesho",
    homeIntro: "Tengeneza mauzo, rekodi malipo ya wateja na shughulikia kazi inayohitaji umakini.",
    newSale: "Mauzo mapya",
    newQuote: "Nukuu mpya",
    recordPayment: "Rekodi malipo",
    processReturn: "Shughulikia marejesho",
    viewTransactions: "Tazama miamala",
    quickActions: "Hatua za haraka",
    startQuoteDetail: "Andaa nukuu ya mteja",
    paymentDetail: "Gawa malipo ya mteja",
    returnDetail: "Tafuta mauzo asili na uanze marekebisho",
    transactionDetail: "Tafuta na ukague mauzo yaliyochapishwa",
    needsAttention: "Inahitaji umakini wako",
    readyToFulfil: "Tayari kutimizwa",
    readyToFulfilDetail: "Oda za wateja zilizoidhinishwa sasa zinaweza kukamilishwa.",
    exceptions: "Hitilafu",
    exceptionsDetail: "Hali za fiskali ambazo hazijatatuliwa na mauzo yaliyobatilishwa yanahitaji ukaguzi.",
    submittedDocuments: "Nyaraka zilizowasilishwa",
    submittedDocumentsDetail: "Nyaraka za mauzo zinasubiri uamuzi.",
    caughtUp: "Umemaliza yaliyo mbele",
    caughtUpDetail: "Hakuna hitilafu za mauzo au oda zilizo tayari katika upeo huu.",
    recentTransactions: "Miamala ya karibuni",
    recentTransactionsDetail: "Mauzo ya mwisho yaliyochapishwa katika upeo huu.",
    viewAll: "Tazama zote",
    type: "Aina",
    number: "Nambari",
    customer: "Mteja",
    amount: "Kiasi",
    status: "Hali",
    date: "Tarehe",
    sale: "Mauzo",
    reversal: "Ubatilisho",
    cash: "Fedha",
    credit: "Mkopo",
    posted: "Imechapishwa",
    reversed: "Imebatilishwa",
    fiscalPending: "Fiskali inasubiri",
    fiscalFailed: "Fiskali imeshindwa",
    fiscalNotConfigured: "Fiskali haijasanidiwa",
    openTransaction: "Fungua muamala",
    noTransactions: "Bado hakuna mauzo yaliyochapishwa katika upeo huu.",
    completeFirstSale: "Kamilisha mauzo ya kwanza",
    searchTransactions: "Tafuta miamala",
    searchPlaceholder: "Tafuta risiti au mteja…",
    clearSearch: "Futa utafutaji",
    noMatches: "Hakuna miamala inayolingana na utafutaji huu.",
    allStatuses: "Hali zote",
    postedOnly: "Yaliyochapishwa",
    reversedOnly: "Yaliyobatilishwa",
    exceptionsOnly: "Hitilafu",
    results: "matokeo",
    previousPage: "Ukurasa uliopita",
    nextPage: "Ukurasa unaofuata",
    transactionRegister: "Rejista ya miamala",
    transactionRegisterIntro: "Tafuta mauzo yaliyochapishwa na ufungue rekodi asili ya biashara.",
    returnsRegister: "Marejesho na marekebisho",
    returnsRegisterIntro: "Tafuta mauzo asili yaliyochapishwa na uanze marekebisho yaliyoidhinishwa.",
    eligibleSales: "Mauzo yanayoweza kurekebishwa",
    returnHint: "Chagua mauzo asili unayohitaji kurekebisha. Rekodi iliyochapishwa haitabadilishwa.",
  },
} as const;

export type SalesCopyKey = keyof typeof catalog.en;

export function salesCopy(locale: Locale, key: SalesCopyKey): string {
  return catalog[locale][key];
}
