"use client";

import { useState } from "react";
import { useLanguage } from "@/components/language-provider";
import { LiveBadge } from "@/components/live-sales/live-state";
import { text } from "@/lib/i18n";
import type { CommercialWorkspace, MasterEntityType, MasterRevision, PublicProblem, RFQ, SourcingAward, SupplierQuote } from "@/live-api/types";

async function command(body:unknown){const response=await fetch("/api/live/commercial",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify(body)});const payload=await response.json();if(!response.ok)throw payload;return payload;}

export function SourcingWorkbench({workspace}:{workspace:CommercialWorkspace}){
 const {l}=useLanguage();const [commercial,setCommercial]=useState(workspace.commercial);const [entityType,setEntityType]=useState<MasterEntityType>("SUPPLIER");const [code,setCode]=useState("");const [name,setName]=useState("");const [productId,setProductId]=useState(workspace.products[0]?.id??"");const [supplierId,setSupplierId]=useState(workspace.suppliers[0]?.id??"");const [quantity,setQuantity]=useState(1);const [unitPrice,setUnitPrice]=useState(0);const [rfqId,setRFQId]=useState("");const [reason,setReason]=useState("Controlled commercial record created for approved business purpose");const [busy,setBusy]=useState(false);const [problem,setProblem]=useState<PublicProblem|null>(null);
 const selectedRFQ=commercial.rfqs.find((item)=>item.id===rfqId);const submittedQuotes=commercial.quotes.filter((item)=>item.rfq_id===rfqId&&item.status==="SUBMITTED").toSorted((a,b)=>a.total_minor-b.total_minor);
 async function run<T>(action:()=>Promise<T>,apply:(value:T)=>void){setBusy(true);setProblem(null);try{apply(await action())}catch(error){setProblem(error as PublicProblem)}finally{setBusy(false)}}
 function createMaster(event:React.FormEvent){event.preventDefault();const supplier=entityType==="SUPPLIER"?{code,name,tax_id:"",email:"",phone:"",payment_terms_days:30,active:true}:undefined;const product=entityType==="PRODUCT"?{sku:code,name,base_unit_code:"EA",currency:workspace.context.currency,list_price_minor:Math.max(unitPrice,1),standard_cost_minor:Math.max(Math.floor(unitPrice*.7),0),tax_code:"VAT18",revenue_account_id:"4000",cogs_account_id:"5000",inventory_account_id:"1200",active:true}:undefined;void run(()=>command({action:"create_master",command:{entity_type:entityType,supplier,product,reason}}) as Promise<MasterRevision>,value=>setCommercial(current=>({...current,revisions:[value,...current.revisions]})));}
 function transitionMaster(item:MasterRevision,status:"SUBMITTED"|"ACTIVE"|"REJECTED"){void run(()=>command({action:"transition_master",id:item.id,status,reason:`Authorized ${status.toLowerCase()} master-data decision`}) as Promise<MasterRevision>,value=>setCommercial(current=>({...current,revisions:current.revisions.map(v=>v.id===value.id?{...v,...value}:v)})));}
 function createRFQ(event:React.FormEvent){event.preventDefault();void run(()=>command({action:"create_rfq",command:{currency:workspace.context.currency,response_due_at:new Date(Date.now()+3*86400000).toISOString(),reason,lines:[{product_id:productId,quantity}]}}) as Promise<RFQ>,value=>{setRFQId(value.id);setCommercial(current=>({...current,rfqs:[value,...current.rfqs]}))});}
 function transitionRFQ(item:RFQ,status:"SUBMITTED"|"APPROVED"|"CANCELLED"){void run(()=>command({action:"transition_rfq",id:item.id,status,reason:`Authorized ${status.toLowerCase()} sourcing decision`}) as Promise<RFQ>,value=>setCommercial(current=>({...current,rfqs:current.rfqs.map(v=>v.id===value.id?{...v,...value}:v)})));}
 function createQuote(event:React.FormEvent){event.preventDefault();if(!selectedRFQ)return;void run(()=>command({action:"create_quote",command:{rfq_id:selectedRFQ.id,supplier_id:supplierId,reference:`QUOTE-${Date.now()}`,currency:selectedRFQ.currency,delivery_days:3,payment_terms_days:30,valid_until:new Date(Date.now()+10*86400000).toISOString(),reason,lines:selectedRFQ.lines.map(line=>({product_id:line.product_id,quantity:line.quantity,unit_price_minor:unitPrice}))}}) as Promise<SupplierQuote>,value=>setCommercial(current=>({...current,quotes:[value,...current.quotes]})));}
 function submitQuote(item:SupplierQuote){void run(()=>command({action:"submit_quote",id:item.id,reason:"Supplier quotation submitted for governed comparison"}) as Promise<SupplierQuote>,value=>setCommercial(current=>({...current,quotes:current.quotes.map(v=>v.id===value.id?{...v,...value}:v)})));}
 function award(item:SupplierQuote){if(!selectedRFQ)return;void run(()=>command({action:"award_rfq",id:selectedRFQ.id,quoteId:item.id,reason:"Best evaluated compliant supplier selected"}) as Promise<SourcingAward>,value=>setCommercial(current=>({...current,rfqs:current.rfqs.map(v=>v.id===selectedRFQ.id?{...v,status:"CLOSED"}:v),quotes:current.quotes.map(v=>v.rfq_id===selectedRFQ.id?{...v,status:v.id===item.id?"SELECTED":"REJECTED"}:v),awards:[value,...current.awards]})));}
 return <section className="page-stack sourcing-workbench">
  <header className="module-header"><div><p className="eyebrow">{l(text("Competitive sourcing", "Ununuzi wa ushindani"))}</p><h1>{l(text("Supplier and product governance", "Usimamizi wa wasambazaji na bidhaa"))}</h1><p>{l(text("Maker-checker masters, comparable RFQs, and traceable purchase-order awards.","Data inayokaguliwa, RFQ zinazolinganishwa, na tuzo za oda zinazofuatilika."))}</p></div><LiveBadge context={workspace.context}/></header>
  <div className="workspace-grid"><section className="card operation-compose"><div className="card-heading"><div><h2>{l(text("Master-data revision","Marekebisho ya data msingi"))}</h2><p>{l(text("Changes become operational only after independent activation.","Mabadiliko yanaanza kutumika baada ya idhini huru."))}</p></div></div><form className="operation-form" onSubmit={createMaster}><label>{l(text("Entity","Aina"))}<select value={entityType} onChange={e=>setEntityType(e.target.value as MasterEntityType)}><option value="SUPPLIER">SUPPLIER</option><option value="PRODUCT">PRODUCT</option></select></label><label>{entityType==="SUPPLIER"?l(text("Supplier code","Msimbo wa msambazaji")):l(text("SKU","SKU"))}<input required value={code} onChange={e=>setCode(e.target.value)}/></label><label>{l(text("Name","Jina"))}<input required value={name} onChange={e=>setName(e.target.value)}/></label>{entityType==="PRODUCT"?<label>{l(text("List price (minor)","Bei ya orodha (senti)"))}<input min="1" type="number" value={unitPrice} onChange={e=>setUnitPrice(Number(e.target.value))}/></label>:null}<label className="operation-reason">{l(text("Business reason","Sababu ya biashara"))}<textarea minLength={8} required value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy} className="primary-button">{l(text("Create revision","Unda marekebisho"))}</button></form></section>
  <section className="card operation-compose"><div className="card-heading"><div><h2>{l(text("Request for quotation","Ombi la bei"))}</h2><p>{l(text("Every quotation must match the approved RFQ lines.","Kila bei lazima ilingane na mistari ya RFQ iliyoidhinishwa."))}</p></div></div><form className="operation-form" onSubmit={createRFQ}><label>{l(text("Product","Bidhaa"))}<select value={productId} onChange={e=>setProductId(e.target.value)}>{workspace.products.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select></label><label>{l(text("Quantity","Kiasi"))}<input min="1" type="number" value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label><button disabled={busy||!productId} className="primary-button">{l(text("Create RFQ","Unda RFQ"))}</button></form><hr/><form className="operation-form" onSubmit={createQuote}><label>{l(text("Approved RFQ","RFQ iliyoidhinishwa"))}<select value={rfqId} onChange={e=>setRFQId(e.target.value)}><option value="">{l(text("Select RFQ","Chagua RFQ"))}</option>{commercial.rfqs.filter(r=>r.status==="APPROVED").map(r=><option key={r.id} value={r.id}>{r.number}</option>)}</select></label><label>{l(text("Supplier","Msambazaji"))}<select value={supplierId} onChange={e=>setSupplierId(e.target.value)}>{workspace.suppliers.filter(s=>s.active).map(s=><option key={s.id} value={s.id}>{s.code} · {s.name}</option>)}</select></label><label>{l(text("Quoted unit price (minor)","Bei iliyotolewa (senti)"))}<input min="1" type="number" value={unitPrice} onChange={e=>setUnitPrice(Number(e.target.value))}/></label><button disabled={busy||!selectedRFQ||!supplierId||unitPrice<1} className="secondary-button">{l(text("Record quotation","Rekodi bei"))}</button></form></section></div>
  {problem?<div className="sale-problem" role="alert"><span><strong>{problem.code}</strong>{problem.detail}</span></div>:null}
  <section className="card records-card"><div className="records-toolbar"><div><h2>{l(text("Approval queue and comparisons","Foleni ya idhini na ulinganisho"))}</h2><span>{commercial.revisions.length+commercial.rfqs.length+commercial.quotes.length}</span></div></div><div className="table-scroll"><table className="data-table"><thead><tr><th>{l(text("Record","Rekodi"))}</th><th>{l(text("Status","Hali"))}</th><th>{l(text("Value","Thamani"))}</th><th>{l(text("Controlled action","Hatua inayodhibitiwa"))}</th></tr></thead><tbody>{commercial.revisions.map(item=><tr key={item.id}><td>{item.entity_type} · {item.supplier?.code??item.product?.sku}</td><td>{item.status}</td><td>{item.supplier?.name??item.product?.name}</td><td>{item.status==="DRAFT"?<button disabled={busy} className="secondary-button" onClick={()=>transitionMaster(item,"SUBMITTED")}>SUBMIT</button>:item.status==="SUBMITTED"?<><button disabled={busy} className="secondary-button" onClick={()=>transitionMaster(item,"ACTIVE")}>ACTIVATE</button><button disabled={busy} className="secondary-button" onClick={()=>transitionMaster(item,"REJECTED")}>REJECT</button></>:null}</td></tr>)}{commercial.rfqs.map(item=><tr key={item.id}><td><button className="table-link" onClick={()=>setRFQId(item.id)}>{item.number}</button></td><td>{item.status}</td><td>{item.lines.reduce((sum,line)=>sum+line.quantity,0)} {l(text("units","vipimo"))}</td><td>{item.status==="DRAFT"?<button disabled={busy} className="secondary-button" onClick={()=>transitionRFQ(item,"SUBMITTED")}>SUBMIT</button>:item.status==="SUBMITTED"?<button disabled={busy} className="secondary-button" onClick={()=>transitionRFQ(item,"APPROVED")}>APPROVE</button>:null}</td></tr>)}{commercial.quotes.map(item=><tr key={item.id}><td>{item.reference}</td><td>{item.status}</td><td>{item.total_minor.toLocaleString()} {item.currency}</td><td>{item.status==="DRAFT"?<button disabled={busy} className="secondary-button" onClick={()=>submitQuote(item)}>SUBMIT</button>:item.status==="SUBMITTED"&&item.rfq_id===rfqId?<button disabled={busy} className="primary-button" onClick={()=>award(item)}>AWARD</button>:null}</td></tr>)}</tbody></table></div>{selectedRFQ&&submittedQuotes.length>0?<div className="card-heading"><div><h3>{l(text("Comparable bids, lowest first","Bei zinazolinganishwa, ndogo kwanza"))}</h3><p>{submittedQuotes.map(q=>`${q.reference}: ${q.total_minor.toLocaleString()} ${q.currency}`).join(" · ")}</p></div></div>:null}</section>
 </section>;
}
