"use client";
import { useState } from "react";
import { useLanguage } from "@/components/language-provider";
import { text } from "@/lib/i18n";
import { formatMinorUnits } from "@/live-api/format";
import type { PeopleSnapshot, PeopleWorkspace, PublicProblem } from "@/live-api/types";
type Action = { action: string; id?: string; command: unknown };
async function send(body: Action): Promise<unknown> { const response = await fetch("/api/live/hr", { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify(body) }); const value: unknown = await response.json(); if (!response.ok) throw value; return value; }
function asProblem(v: unknown): PublicProblem { return v && typeof v === "object" && "detail" in v ? v as PublicProblem : { type: "about:blank", title: "Failed", status: 500, code: "people_failed", detail: v instanceof Error ? v.message : "People command failed." }; }
export function PeopleWorkbench({ workspace }: { workspace: PeopleWorkspace }) {
  const { l, locale } = useLanguage(); const [data] = useState(workspace.people); const [busy, setBusy] = useState(false); const [failure, setFailure] = useState<PublicProblem | null>(null); const permissions = new Set(workspace.context.permissions); const money = (v: number) => formatMinorUnits(v, workspace.context.currency, locale);
  async function run(body: Action) { setBusy(true); setFailure(null); try { await send(body); location.reload(); } catch (e) { setFailure(asProblem(e)); setBusy(false); } }
  const employees = new Map(data.employees.map((e) => [e.id, e]));
  return <section className="page-stack"><header className="module-header"><div><p className="eyebrow">{l(text("People, pay and accountability", "Watu, mishahara na uwajibikaji"))}</p><h1>{l(text("Human resources & payroll", "Rasilimali watu na mishahara"))}</h1><p>{l(text("Govern employee records, attendance, leave, loans, payroll posting and payslips in one legal-company workspace.", "Dhibiti wafanyakazi, mahudhurio, likizo, mikopo, uhasibu wa mishahara na hati za malipo katika kampuni moja."))}</p></div></header>
    {failure ? <div className="problem-banner" role="alert"><strong>{failure.code}</strong><span>{failure.detail}</span></div> : null}
    <section className="metric-grid"><article className="metric-card"><span>{l(text("Active employees", "Wafanyakazi hai"))}</span><strong>{data.employees.filter((e) => e.status === "ACTIVE").length}</strong></article><article className="metric-card"><span>{l(text("Leave awaiting approval", "Likizo zinazosubiri"))}</span><strong>{data.leave_requests.filter((v) => v.status === "SUBMITTED").length}</strong></article><article className="metric-card"><span>{l(text("Loan balance", "Salio la mikopo"))}</span><strong>{money(data.loans.reduce((n, v) => n + v.outstanding_minor, 0))}</strong></article><article className="metric-card"><span>{l(text("Posted payroll", "Mishahara iliyowekwa"))}</span><strong>{data.payroll_runs.filter((v) => v.status === "POSTED").length}</strong></article></section>
    {permissions.has("hr.employees.manage") ? <EmployeeForm disabled={busy} onRun={run} l={l} /> : null}
    <Register title={l(text("Employee register", "Daftari la wafanyakazi"))}><table><thead><tr><th>{l(text("Employee", "Mfanyakazi"))}</th><th>{l(text("Role", "Wadhifa"))}</th><th>{l(text("Hire date", "Tarehe ya kuanza"))}</th><th>{l(text("Salary", "Mshahara"))}</th></tr></thead><tbody>{data.employees.map((e) => <tr key={e.id}><td><strong>{e.number} · {e.full_name}</strong><br /><small>{e.status}</small></td><td>{e.job_title}<br /><small>{e.department}</small></td><td>{new Date(e.hire_date).toLocaleDateString(locale)}</td><td>{money(e.base_salary_minor)}</td></tr>)}</tbody></table></Register>
    <div className="detail-grid"><Register title={l(text("Leave approvals", "Idhini za likizo"))}>{permissions.has("hr.leave.manage") && data.leave_types.length && data.employees.length ? <LeaveForm data={data} disabled={busy} onRun={run} l={l} /> : null}<ul className="timeline-list">{data.leave_requests.map((v) => <li key={v.id}><strong>{employees.get(v.employee_id)?.full_name ?? v.employee_id}</strong><span>{v.days} {l(text("days", "siku"))} · {v.status}</span>{v.status === "DRAFT" && permissions.has("hr.leave.manage") ? <button disabled={busy} className="button button-secondary" onClick={() => run({ action: "transition_leave", id: v.id, command: { status: "SUBMITTED", reason: "Leave evidence submitted for independent review" } })}>{l(text("Submit", "Wasilisha"))}</button> : null}{v.status === "SUBMITTED" && permissions.has("hr.leave.approve") ? <button disabled={busy} className="button button-primary" onClick={() => run({ action: "transition_leave", id: v.id, command: { status: "APPROVED", reason: "Independent leave review and approval complete" } })}>{l(text("Approve", "Idhinisha"))}</button> : null}</li>)}</ul></Register>
    <Register title={l(text("Loans", "Mikopo"))}><ul className="timeline-list">{data.loans.map((v) => <li key={v.id}><strong>{v.reference} · {employees.get(v.employee_id)?.full_name}</strong><span>{money(v.outstanding_minor)} · {v.status}</span><WorkflowActions kind="loan" id={v.id} status={v.status} permissions={permissions} busy={busy} run={run} l={l} /></li>)}</ul></Register></div>
    {permissions.has("hr.payroll.manage") && data.employees.length ? <PayrollForm data={data} accounts={workspace.accounts} disabled={busy} onRun={run} l={l} /> : null}
    <Register title={l(text("Payroll runs & payslips", "Mishahara na hati za malipo"))}><table><thead><tr><th>{l(text("Run", "Mzunguko"))}</th><th>{l(text("Gross", "Jumla"))}</th><th>{l(text("Deductions", "Makato"))}</th><th>{l(text("Net", "Halisi"))}</th><th>{l(text("Control", "Udhibiti"))}</th></tr></thead><tbody>{data.payroll_runs.map((v) => <tr key={v.id}><td><strong>{v.reference}</strong><br /><small>{v.lines.length} {l(text("payslips", "hati"))} · {v.status}</small></td><td>{money(v.gross_minor)}</td><td>{money(v.deductions_minor)}</td><td>{money(v.net_minor)}</td><td><WorkflowActions kind="payroll" id={v.id} status={v.status} permissions={permissions} busy={busy} run={run} l={l} /></td></tr>)}</tbody></table></Register>
  </section>;
}
function Register({ title, children }: { title: string; children: React.ReactNode }) { return <section className="card"><div className="card-heading"><h2>{title}</h2></div><div className="table-scroll">{children}</div></section>; }
type L = (v: { en: string; sw: string }) => string;
function EmployeeForm({ disabled, onRun, l }: { disabled: boolean; onRun: (v: Action) => void; l: L }) { return <form className="bank-import-form" onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); onRun({ action: "create_employee", command: { number: f.get("number"), full_name: f.get("name"), job_title: f.get("job"), department: f.get("department"), currency: "TZS", hire_date: f.get("hire"), base_salary_minor: Math.round(Number(f.get("salary")) * 100) } }); }}><label>{l(text("Employee no.", "Namba"))}<input name="number" required /></label><label>{l(text("Full name", "Jina kamili"))}<input name="name" required /></label><label>{l(text("Job title", "Wadhifa"))}<input name="job" required /></label><label>{l(text("Department", "Idara"))}<input name="department" required /></label><label>{l(text("Hire date", "Tarehe"))}<input name="hire" type="date" required /></label><label>{l(text("Base salary TZS", "Mshahara TZS"))}<input name="salary" type="number" min="0" required /></label><button className="button button-primary" disabled={disabled}>{l(text("Add employee", "Ongeza mfanyakazi"))}</button></form>; }
function LeaveForm({ data, disabled, onRun, l }: { data: PeopleSnapshot; disabled: boolean; onRun: (v: Action) => void; l: L }) { return <form className="action-row" onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); onRun({ action: "create_leave", command: { employee_id: f.get("employee"), leave_type_id: f.get("type"), starts_on: f.get("start"), ends_on: f.get("end"), reason: "Employee leave request with supporting evidence" } }); }}><select name="employee">{data.employees.map((v) => <option key={v.id} value={v.id}>{v.full_name}</option>)}</select><select name="type">{data.leave_types.map((v) => <option key={v.id} value={v.id}>{v.name_en}</option>)}</select><input name="start" type="date" required /><input name="end" type="date" required /><button className="button button-secondary" disabled={disabled}>{l(text("Request", "Omba"))}</button></form>; }
function WorkflowActions({ kind, id, status, permissions, busy, run, l }: { kind: "loan" | "payroll"; id: string; status: string; permissions: Set<string>; busy: boolean; run: (v: Action) => void; l: L }) { const manage = `hr.${kind === "loan" ? "loans" : "payroll"}.manage`; const approve = `hr.${kind === "loan" ? "loans" : "payroll"}.approve`; if (status === "DRAFT" && permissions.has(manage)) return <button className="button button-secondary" disabled={busy} onClick={() => run({ action: `transition_${kind}`, id, command: { status: "SUBMITTED", reason: "Workflow evidence submitted for independent review" } })}>{l(text("Submit", "Wasilisha"))}</button>; if (status === "SUBMITTED" && permissions.has(approve)) return <button className="button button-primary" disabled={busy} onClick={() => run({ action: `transition_${kind}`, id, command: { status: "APPROVED", reason: "Independent workflow approval completed" } })}>{l(text("Approve", "Idhinisha"))}</button>; if (status === "APPROVED" && permissions.has(approve)) return <button className="button button-primary" disabled={busy} onClick={() => run({ action: `transition_${kind}`, id, command: { status: "POSTED", reason: "Approved workflow posted to controlled ledgers" } })}>{l(text("Post", "Weka"))}</button>; return null; }
function PayrollForm({ data, accounts, disabled, onRun, l }: { data: PeopleSnapshot; accounts: PeopleWorkspace["accounts"]; disabled: boolean; onRun: (v: Action) => void; l: L }) { const expenses = accounts.filter((a) => a.type === "EXPENSE"), liabilities = accounts.filter((a) => a.type === "LIABILITY"); return <form className="bank-import-form" onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); const gross = Math.round(Number(f.get("gross")) * 100), other = Math.round(Number(f.get("deduction")) * 100), loan = Math.round(Number(f.get("loan")) * 100); onRun({ action: "create_payroll", command: { reference: f.get("reference"), currency: "TZS", period_start: f.get("start"), period_end: f.get("end"), payment_date: f.get("pay"), salary_expense_account_id: f.get("expense"), payroll_payable_account_id: f.get("payable"), deduction_liability_account_id: f.get("liability"), reason: "Approved payroll inputs prepared for controlled posting", lines: [{ employee_id: f.get("employee"), gross_minor: gross, other_deductions_minor: other, loan_deduction_minor: loan, net_minor: gross - other - loan }] } }); }}><label>{l(text("Payroll reference", "Rejea ya mshahara"))}<input name="reference" required /></label><label>{l(text("Employee / payslip", "Mfanyakazi / hati"))}<select name="employee">{data.employees.map((v) => <option key={v.id} value={v.id}>{v.full_name}</option>)}</select></label><label>{l(text("Gross TZS", "Jumla TZS"))}<input name="gross" type="number" min="0.01" required /></label><label>{l(text("Other deductions", "Makato mengine"))}<input name="deduction" type="number" min="0" defaultValue="0" /></label><label>{l(text("Loan deduction", "Kato la mkopo"))}<input name="loan" type="number" min="0" defaultValue="0" /></label><label>{l(text("Period start", "Mwanzo"))}<input name="start" type="date" required /></label><label>{l(text("Period end", "Mwisho"))}<input name="end" type="date" required /></label><label>{l(text("Payment date", "Tarehe ya malipo"))}<input name="pay" type="date" required /></label><label>{l(text("Salary expense", "Gharama ya mshahara"))}<select name="expense">{expenses.map((a) => <option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></label><label>{l(text("Payroll payable", "Deni la mshahara"))}<select name="payable">{liabilities.map((a) => <option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></label><label>{l(text("Deduction liability", "Deni la makato"))}<select name="liability">{liabilities.map((a) => <option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></label><button className="button button-primary" disabled={disabled}>{l(text("Create payroll", "Unda mshahara"))}</button></form>; }
