"use client";

import { useState } from "react";
import { useLanguage } from "@/components/language-provider";
import { text } from "@/lib/i18n";
import type { PayrollArtifact, PeopleWorkspace, PublicProblem, ShiftAssignment, ShiftTemplate, WorkforceStatus } from "@/live-api/types";

type Action = { action: string; id?: string; status?: WorkforceStatus; reason?: string; command?: unknown };
async function send<T>(body: Action): Promise<T> { const response=await fetch("/api/live/hr",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify(body)});const value=await response.json();if(!response.ok)throw value;return value as T; }
function problem(value:unknown):PublicProblem{return value&&typeof value==="object"&&"detail" in value?value as PublicProblem:{type:"about:blank",title:"Failed",status:500,code:"workforce_failed",detail:"Workforce command failed."}}
function download(artifact:PayrollArtifact){if(!artifact.content)return;const url=URL.createObjectURL(new Blob([artifact.content],{type:artifact.media_type}));const anchor=document.createElement("a");anchor.href=url;anchor.download=artifact.file_name;anchor.click();URL.revokeObjectURL(url)}

export function WorkforceWorkbench({workspace}:{workspace:PeopleWorkspace}){
 const{l,locale}=useLanguage();const[data,setData]=useState(workspace.workforce);const[busy,setBusy]=useState(false);const[failure,setFailure]=useState<PublicProblem|null>(null);const permissions=new Set(workspace.context.permissions);const employees=new Map(workspace.people.employees.map(item=>[item.id,item]));const templates=new Map(data.templates.map(item=>[item.id,item]));
 async function run<T>(work:()=>Promise<T>,apply?:(value:T)=>void){setBusy(true);setFailure(null);try{const value=await work();apply?.(value)}catch(error){setFailure(problem(error))}finally{setBusy(false)}}
 function transitionTemplate(item:ShiftTemplate,status:WorkforceStatus){void run(()=>send<ShiftTemplate>({action:"transition_shift_template",id:item.id,status,reason:`Authorized ${status.toLowerCase()} shift-template decision`}),(value)=>setData(current=>({...current,templates:current.templates.map(entry=>entry.id===value.id?{...entry,...value}:entry)})))}
 function transitionAssignment(item:ShiftAssignment,status:WorkforceStatus){void run(()=>send<ShiftAssignment>({action:"transition_shift_assignment",id:item.id,status,reason:`Authorized ${status.toLowerCase()} shift-assignment decision`}),(value)=>setData(current=>({...current,assignments:current.assignments.map(entry=>entry.id===value.id?{...entry,...value}:entry)})))}
 return <section className="page-stack"><header className="module-header"><div><p className="eyebrow">{l(text("Workforce operations","Uendeshaji wa wafanyakazi"))}</p><h1>{l(text("Schedules, documents & payroll outputs","Ratiba, nyaraka na matokeo ya mishahara"))}</h1><p>{l(text("Independent shift approval, expiry-aware document evidence, and exports pinned to approved configuration.","Idhini huru ya zamu, ushahidi wa nyaraka wenye muda, na faili zinazofungwa kwa usanidi ulioidhinishwa."))}</p></div></header>
 {failure?<div className="problem-banner" role="alert"><strong>{failure.code}</strong><span>{failure.detail}</span></div>:null}
 <section className="metric-grid"><article className="metric-card"><span>{l(text("Active templates","Violezo hai"))}</span><strong>{data.templates.filter(item=>item.status==="ACTIVE").length}</strong></article><article className="metric-card"><span>{l(text("Approved assignments","Mgao ulioidhinishwa"))}</span><strong>{data.assignments.filter(item=>item.status==="APPROVED").length}</strong></article><article className="metric-card"><span>{l(text("Expiry-dated documents","Nyaraka zenye tarehe ya mwisho"))}</span><strong>{data.documents.filter(item=>Boolean(item.expires_on)).length}</strong></article><article className="metric-card"><span>{l(text("Payroll artifacts","Faili za mishahara"))}</span><strong>{data.payroll_artifacts.length}</strong></article></section>
 <div className="workspace-grid">{permissions.has("hr.shifts.manage")?<ShiftForms workspace={workspace} data={data} busy={busy} run={run} l={l}/>:null}{permissions.has("hr.documents.manage")?<DocumentForm workspace={workspace} busy={busy} run={run} l={l}/>:null}</div>
 <section className="card records-card"><div className="records-toolbar"><div><h2>{l(text("Shift governance","Usimamizi wa zamu"))}</h2><span>{data.templates.length+data.assignments.length}</span></div></div><div className="table-scroll"><table><thead><tr><th>{l(text("Record","Rekodi"))}</th><th>{l(text("Effective","Inatumika"))}</th><th>{l(text("Status","Hali"))}</th><th>{l(text("Control","Udhibiti"))}</th></tr></thead><tbody>{data.templates.map(item=><tr key={item.id}><td><strong>{item.code} · {locale==="sw"?item.name_sw:item.name_en}</strong><br/><small>{clock(item.start_minute)}–{clock(item.end_minute)} · {item.break_minutes}m</small></td><td>{new Date(item.effective_from).toLocaleDateString(locale)}</td><td>{item.status}</td><td>{item.status==="DRAFT"?<button disabled={busy} className="button button-secondary" onClick={()=>transitionTemplate(item,"SUBMITTED")}>{l(text("Submit","Wasilisha"))}</button>:item.status==="SUBMITTED"?<button disabled={busy} className="button button-primary" onClick={()=>transitionTemplate(item,"ACTIVE")}>{l(text("Activate","Washa"))}</button>:null}</td></tr>)}{data.assignments.map(item=><tr key={item.id}><td><strong>{employees.get(item.employee_id)?.full_name??item.employee_id}</strong><br/><small>{templates.get(item.shift_template_id)?.code??item.shift_template_id}</small></td><td>{new Date(item.starts_on).toLocaleDateString(locale)}–{new Date(item.ends_on).toLocaleDateString(locale)}</td><td>{item.status}</td><td>{item.status==="DRAFT"?<button disabled={busy} className="button button-secondary" onClick={()=>transitionAssignment(item,"SUBMITTED")}>{l(text("Submit","Wasilisha"))}</button>:item.status==="SUBMITTED"?<button disabled={busy} className="button button-primary" onClick={()=>transitionAssignment(item,"APPROVED")}>{l(text("Approve","Idhinisha"))}</button>:null}</td></tr>)}</tbody></table></div></section>
 <div className="workspace-grid"><section className="card records-card"><div className="card-heading"><h2>{l(text("Employee document register","Daftari la nyaraka"))}</h2></div><div className="table-scroll"><table><thead><tr><th>{l(text("Document","Hati"))}</th><th>{l(text("Employee","Mfanyakazi"))}</th><th>{l(text("Expires","Inaisha"))}</th></tr></thead><tbody>{data.documents.map(item=><tr key={item.id}><td><strong>{item.document_type} · {item.title}</strong><br/><small>{item.classification} · {item.sha256.slice(0,12)}…</small></td><td>{employees.get(item.employee_id)?.full_name}</td><td>{item.expires_on?new Date(item.expires_on).toLocaleDateString(locale):"—"}</td></tr>)}</tbody></table></div></section><PayrollExports workspace={workspace} data={data} busy={busy} run={run} l={l}/></div>
 </section>
}
type L=(value:{en:string;sw:string})=>string;type Runner=<T>(work:()=>Promise<T>,apply?:(value:T)=>void)=>Promise<void>;const clock=(minute:number)=>`${String(Math.floor(minute/60)).padStart(2,"0")}:${String(minute%60).padStart(2,"0")}`;
function ShiftForms({workspace,data,busy,run,l}:{workspace:PeopleWorkspace;data:PeopleWorkspace["workforce"];busy:boolean;run:Runner;l:L}){return <section className="card operation-compose"><div className="card-heading"><h2>{l(text("Schedule planning","Upangaji wa ratiba"))}</h2></div><form className="bank-import-form" onSubmit={event=>{event.preventDefault();const f=new FormData(event.currentTarget);void run(()=>send<ShiftTemplate>({action:"create_shift_template",command:{code:f.get("code"),name_en:f.get("name_en"),name_sw:f.get("name_sw"),start_minute:Number(f.get("start")),end_minute:Number(f.get("end")),break_minutes:Number(f.get("break")),weekday_mask:31,effective_from:f.get("effective"),reason:"Create governed workforce schedule"}}),()=>location.reload())}}><label>{l(text("Code","Msimbo"))}<input name="code" required/></label><label>{l(text("English name","Jina la Kiingereza"))}<input name="name_en" required/></label><label>{l(text("Swahili name","Jina la Kiswahili"))}<input name="name_sw" required/></label><label>{l(text("Start minute","Dakika ya kuanza"))}<input name="start" type="number" min="0" max="1439" defaultValue="480" required/></label><label>{l(text("End minute","Dakika ya mwisho"))}<input name="end" type="number" min="0" max="1439" defaultValue="1020" required/></label><label>{l(text("Break minutes","Dakika za mapumziko"))}<input name="break" type="number" min="0" max="720" defaultValue="60" required/></label><label>{l(text("Effective from","Inaanza"))}<input name="effective" type="date" required/></label><button className="button button-primary" disabled={busy}>{l(text("Create shift","Unda zamu"))}</button></form><hr/><form className="action-row" onSubmit={event=>{event.preventDefault();const f=new FormData(event.currentTarget);void run(()=>send<ShiftAssignment>({action:"create_shift_assignment",command:{employee_id:f.get("employee"),shift_template_id:f.get("template"),starts_on:f.get("start"),ends_on:f.get("end"),reason:"Assign employee to approved workforce schedule"}}),()=>location.reload())}}><select name="employee" required>{workspace.people.employees.filter(item=>item.status==="ACTIVE").map(item=><option key={item.id} value={item.id}>{item.full_name}</option>)}</select><select name="template" required>{data.templates.filter(item=>item.status==="ACTIVE").map(item=><option key={item.id} value={item.id}>{item.code}</option>)}</select><input name="start" type="date" required/><input name="end" type="date" required/><button className="button button-secondary" disabled={busy}>{l(text("Assign","Panga"))}</button></form></section>}
function DocumentForm({workspace,busy,run,l}:{workspace:PeopleWorkspace;busy:boolean;run:Runner;l:L}){return <section className="card operation-compose"><div className="card-heading"><h2>{l(text("Register document evidence","Sajili ushahidi wa hati"))}</h2></div><form className="bank-import-form" onSubmit={event=>{event.preventDefault();const f=new FormData(event.currentTarget);void run(()=>send({action:"register_employee_document",command:{employee_id:f.get("employee"),document_type:f.get("type"),title:f.get("title"),object_key:f.get("object"),sha256:f.get("sha"),media_type:"application/pdf",classification:f.get("classification"),expires_on:f.get("expires")||undefined,reason:"Register verified employee document evidence"}}),()=>location.reload())}}><label>{l(text("Employee","Mfanyakazi"))}<select name="employee">{workspace.people.employees.map(item=><option key={item.id} value={item.id}>{item.full_name}</option>)}</select></label><label>{l(text("Document type","Aina ya hati"))}<input name="type" required/></label><label>{l(text("Title","Kichwa"))}<input name="title" required/></label><label>{l(text("Protected object key","Ufunguo wa faili salama"))}<input name="object" required/></label><label>SHA-256<input name="sha" pattern="[0-9a-fA-F]{64}" required/></label><label>{l(text("Classification","Uainishaji"))}<select name="classification"><option>RESTRICTED</option><option>CONFIDENTIAL</option><option>INTERNAL</option></select></label><label>{l(text("Expires","Inaisha"))}<input name="expires" type="date"/></label><button className="button button-primary" disabled={busy}>{l(text("Register metadata","Sajili metadata"))}</button></form></section>}
function PayrollExports({workspace,data,busy,run,l}:{workspace:PeopleWorkspace;data:PeopleWorkspace["workforce"];busy:boolean;run:Runner;l:L}){const posted=workspace.people.payroll_runs.filter(item=>item.status==="POSTED");return <section className="card records-card"><div className="card-heading"><h2>{l(text("Configured payroll outputs","Faili za mishahara zilizosanidiwa"))}</h2></div>{workspace.context.permissions.includes("hr.payroll.export")?<form className="action-row" onSubmit={event=>{event.preventDefault();const f=new FormData(event.currentTarget);void run(()=>send<PayrollArtifact>({action:"generate_payroll_artifact",id:String(f.get("payroll")),command:{configuration_id:f.get("configuration"),format:f.get("format")}}),download)}}><select name="payroll" required>{posted.map(item=><option key={item.id} value={item.id}>{item.reference}</option>)}</select><select name="configuration" required>{workspace.configurations.map(item=><option key={item.id} value={item.id}>{item.key} · {item.name_en}</option>)}</select><select name="format"><option>BANK_CSV</option><option>STATUTORY_CSV</option></select><button className="button button-primary" disabled={busy||posted.length===0||workspace.configurations.length===0}>{l(text("Generate & download","Tengeneza na pakua"))}</button></form>:null}<ul className="timeline-list">{data.payroll_artifacts.map(item=><li key={item.id}><strong>{item.file_name}</strong><span>{item.format} · {item.row_count} {l(text("rows","mistari"))} · {item.sha256.slice(0,12)}…</span></li>)}</ul></section>}
