"use client";

import { useState } from "react";
import { useLanguage } from "@/components/language-provider";
import { text } from "@/lib/i18n";
import { formatMinorUnits } from "@/live-api/format";
import type { BalanceSheet, CashFlow, ExportFinancialReportCommand, FinancialReportsWorkspace, GeneralLedger, ProfitAndLoss, PublicProblem, ReportExportArtifact, TrialBalance } from "@/live-api/types";

type View = "TRIAL_BALANCE" | "GENERAL_LEDGER" | "PROFIT_AND_LOSS" | "BALANCE_SHEET" | "CASH_FLOW";
const views: View[] = ["TRIAL_BALANCE", "GENERAL_LEDGER", "PROFIT_AND_LOSS", "BALANCE_SHEET", "CASH_FLOW"];
const labels: Record<View, ReturnType<typeof text>> = {
  TRIAL_BALANCE: text("Trial balance", "Mizania ya majaribio"), GENERAL_LEDGER: text("General ledger", "Leja kuu"),
  PROFIT_AND_LOSS: text("Profit & loss", "Faida na hasara"), BALANCE_SHEET: text("Balance sheet", "Taarifa ya hali ya fedha"), CASH_FLOW: text("Cash flow", "Mtiririko wa fedha"),
};
function problem(value: unknown): PublicProblem { if (value && typeof value === "object" && "detail" in value) return value as PublicProblem; return { type: "about:blank", title: "Report failed", status: 500, code: "report_failed", detail: value instanceof Error ? value.message : "The report could not be completed." }; }
async function payload(response: Response): Promise<unknown> { const value: unknown = await response.json(); if (!response.ok) throw value; return value; }
function download(artifact: ReportExportArtifact) { const bytes = Uint8Array.from(atob(artifact.content_base64), (character) => character.charCodeAt(0)); const url = URL.createObjectURL(new Blob([bytes], { type: artifact.media_type })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = artifact.filename; anchor.click(); URL.revokeObjectURL(url); }

export function FinancialReports({ workspace }: { workspace: FinancialReportsWorkspace }) {
  const { l, locale } = useLanguage(); const money = (value: number) => formatMinorUnits(value, "TZS", locale);
  const [view, setView] = useState<View>("TRIAL_BALANCE"); const [from, setFrom] = useState(workspace.from); const [to, setTo] = useState(workspace.to); const [asOf, setAsOf] = useState(workspace.asOf); const [account, setAccount] = useState(workspace.accounts[0]?.id ?? "");
  const [trial, setTrial] = useState(workspace.trialBalance); const [ledger, setLedger] = useState<GeneralLedger | null>(null); const [profitLoss, setProfitLoss] = useState(workspace.profitAndLoss); const [balance, setBalance] = useState(workspace.balanceSheet); const [cash, setCash] = useState(workspace.cashFlow); const [busy, setBusy] = useState(false); const [failure, setFailure] = useState<PublicProblem | null>(null);
  const canExport = workspace.context.permissions.includes("reports.financial.export");

  async function run(selected = view, selectedAccount = account) { setBusy(true); setFailure(null); try { const query = selected === "TRIAL_BALANCE" || selected === "BALANCE_SHEET" ? `as_of=${encodeURIComponent(asOf)}` : `from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`; const suffix = selected.toLowerCase().replaceAll("_", "-"); const accountQuery = selected === "GENERAL_LEDGER" ? `&account_id=${encodeURIComponent(selectedAccount)}` : ""; const result = await payload(await fetch(`/api/live/reports/financial/${suffix}?${query}${accountQuery}`, { cache: "no-store" })); if (selected === "TRIAL_BALANCE") setTrial(result as TrialBalance); if (selected === "GENERAL_LEDGER") setLedger(result as GeneralLedger); if (selected === "PROFIT_AND_LOSS") setProfitLoss(result as ProfitAndLoss); if (selected === "BALANCE_SHEET") setBalance(result as BalanceSheet); if (selected === "CASH_FLOW") setCash(result as CashFlow); } catch (error) { setFailure(problem(error)); } finally { setBusy(false); } }
  async function exportCSV() { setBusy(true); setFailure(null); try { const command: ExportFinancialReportCommand = { report_type: view }; if (view === "TRIAL_BALANCE" || view === "BALANCE_SHEET") command.as_of = asOf; else { command.from = from; command.to = to; } if (view === "GENERAL_LEDGER") command.account_id = account; const artifact = await payload(await fetch("/api/live/reports/financial/exports", { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify(command) })) as ReportExportArtifact; download(artifact); } catch (error) { setFailure(problem(error)); } finally { setBusy(false); } }
  function drill(accountId: string) { setAccount(accountId); setView("GENERAL_LEDGER"); void run("GENERAL_LEDGER", accountId); }

  return <section className="page-stack">
    <header className="module-header"><div><p className="eyebrow">{l(text("Record to report", "Rekodi hadi ripoti"))}</p><h1>{l(text("Financial statements", "Taarifa za fedha"))}</h1><p>{l(text("Company-wide statements derived from the immutable general ledger, with account drill-down and retained exports.", "Taarifa za kampuni nzima zinazotokana na leja kuu isiyobadilika, pamoja na uchambuzi wa akaunti na nakala zilizohifadhiwa."))}</p></div></header>
    {failure ? <div className="problem-banner" role="alert"><strong>{failure.code}</strong><span>{failure.detail}</span></div> : null}
    <nav className="action-row" aria-label={l(text("Financial report", "Ripoti ya fedha"))}>{views.map((item) => <button key={item} className={`button ${view === item ? "button-primary" : "button-secondary"}`} onClick={() => setView(item)}>{l(labels[item])}</button>)}</nav>
    <section className="card operation-compose"><form className="bank-import-form" onSubmit={(event) => { event.preventDefault(); void run(); }}>
      {view === "TRIAL_BALANCE" || view === "BALANCE_SHEET" ? <label>{l(text("As of", "Hadi tarehe"))}<input type="date" required value={asOf} onChange={(event) => setAsOf(event.target.value)} /></label> : <><label>{l(text("From", "Kuanzia"))}<input type="date" required value={from} onChange={(event) => setFrom(event.target.value)} /></label><label>{l(text("To", "Hadi"))}<input type="date" required value={to} onChange={(event) => setTo(event.target.value)} /></label></>}
      {view === "GENERAL_LEDGER" ? <label>{l(text("Account", "Akaunti"))}<select required value={account} onChange={(event) => setAccount(event.target.value)}>{workspace.accounts.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label> : null}
      <button className="button button-primary" disabled={busy}>{l(text("Run report", "Endesha ripoti"))}</button>{canExport ? <button type="button" className="button button-secondary" disabled={busy} onClick={exportCSV}>{l(text("Export CSV", "Pakua CSV"))}</button> : null}
    </form></section>
    {view === "TRIAL_BALANCE" ? <><section className="metric-grid"><Metric label={l(text("Total debits", "Jumla ya debiti"))} value={money(trial.total_debit_minor)} /><Metric label={l(text("Total credits", "Jumla ya krediti"))} value={money(trial.total_credit_minor)} /><Metric label={l(text("Reconciliation", "Upatanisho"))} value={trial.balanced ? l(text("Balanced", "Imesawazika")) : l(text("Exception", "Tatizo"))} /></section><StatementTable lines={trial.lines} money={money} onDrill={drill} headers={[l(text("Account", "Akaunti")), l(text("Type", "Aina")), l(text("Debit", "Debiti")), l(text("Credit / amount", "Krediti / kiasi"))]} /></> : null}
    {view === "PROFIT_AND_LOSS" ? <><section className="metric-grid"><Metric label={l(text("Revenue", "Mapato"))} value={money(profitLoss.total_revenue_minor)} /><Metric label={l(text("Expenses", "Gharama"))} value={money(profitLoss.total_expense_minor)} /><Metric label={l(text("Net profit", "Faida halisi"))} value={money(profitLoss.net_profit_minor)} /></section><StatementTable lines={[...profitLoss.revenue, ...profitLoss.expenses]} money={money} onDrill={drill} headers={[l(text("Account", "Akaunti")), l(text("Type", "Aina")), l(text("Debit", "Debiti")), l(text("Credit / amount", "Krediti / kiasi"))]} /></> : null}
    {view === "BALANCE_SHEET" ? <><section className="metric-grid"><Metric label={l(text("Assets", "Mali"))} value={money(balance.total_assets_minor)} /><Metric label={l(text("Liabilities", "Madeni"))} value={money(balance.total_liabilities_minor)} /><Metric label={l(text("Equity", "Mtaji"))} value={money(balance.total_equity_minor)} /></section>{!balance.balanced ? <div className="problem-banner" role="status"><strong>{l(text("Reconciliation exception", "Tatizo la upatanisho"))}</strong><span>{l(text("Review unclassified accounts before relying on this statement.", "Kagua akaunti zisizoainishwa kabla ya kutegemea taarifa hii."))}</span></div> : null}<StatementTable lines={[...balance.assets, ...balance.liabilities, ...balance.equity]} money={money} onDrill={drill} headers={[l(text("Account", "Akaunti")), l(text("Type", "Aina")), l(text("Debit", "Debiti")), l(text("Credit / amount", "Krediti / kiasi"))]} /></> : null}
    {view === "CASH_FLOW" ? <><section className="metric-grid"><Metric label={l(text("Opening cash", "Fedha za mwanzo"))} value={money(cash.opening_cash_minor)} /><Metric label={l(text("Net movement", "Mabadiliko halisi"))} value={money(cash.net_change_minor)} /><Metric label={l(text("Closing cash", "Fedha za mwisho"))} value={money(cash.closing_cash_minor)} /></section>{!cash.reconciled || !cash.classified ? <div className="problem-banner" role="status"><strong>{l(text("Cash-flow review required", "Ukaguzi wa mtiririko wa fedha unahitajika"))}</strong><span>{l(text("Review unclassified cash movements or the opening-to-closing reconciliation before approval.", "Kagua miamala ya fedha isiyoainishwa au upatanisho wa salio la mwanzo hadi mwisho kabla ya idhini."))}</span></div> : null}<CashFlowTable cash={cash} money={money} headers={[l(text("Activity", "Shughuli")), l(text("Date", "Tarehe")), l(text("Source", "Chanzo")), l(text("Memo", "Maelezo")), l(text("Amount", "Kiasi"))]} /></> : null}
    {view === "GENERAL_LEDGER" ? ledger ? <><section className="metric-grid"><Metric label={l(text("Opening balance", "Salio la mwanzo"))} value={money(ledger.opening_balance_minor)} /><Metric label={l(text("Period debits", "Debiti za kipindi"))} value={money(ledger.total_debit_minor)} /><Metric label={l(text("Closing balance", "Salio la mwisho"))} value={money(ledger.closing_balance_minor)} /></section><section className="card"><div className="card-heading"><div><h2>{ledger.account_code} · {ledger.account_name}</h2></div></div><div className="table-scroll"><table><thead><tr><th>{l(text("Date", "Tarehe"))}</th><th>{l(text("Source", "Chanzo"))}</th><th>{l(text("Memo", "Maelezo"))}</th><th>{l(text("Debit", "Debiti"))}</th><th>{l(text("Credit", "Krediti"))}</th><th>{l(text("Balance", "Salio"))}</th></tr></thead><tbody>{ledger.entries.map((entry) => <tr key={entry.journal_line_id}><td>{entry.occurred_at.slice(0, 10)}</td><td>{entry.source_type}</td><td>{entry.memo || "—"}</td><td>{entry.debit_minor ? money(entry.debit_minor) : "—"}</td><td>{entry.credit_minor ? money(entry.credit_minor) : "—"}</td><td>{money(entry.running_balance_minor)}</td></tr>)}</tbody></table></div></section></> : <section className="card"><p>{l(text("Choose an account and run the ledger.", "Chagua akaunti na uendeshe leja."))}</p></section> : null}
  </section>;
}

function Metric({ label, value }: { label: string; value: string }) { return <article className="metric-card"><p className="metric-label">{label}</p><strong>{value}</strong></article>; }
function StatementTable({ lines, money, onDrill, headers }: { lines: Array<{ account_id: string; code: string; name: string; type: string; amount_minor: number; debit_minor?: number; credit_minor?: number }>; money: (value: number) => string; onDrill: (id: string) => void; headers: string[] }) { return <section className="card"><div className="table-scroll"><table><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{lines.map((line) => <tr key={line.account_id}><td><button className="button button-ghost" onClick={() => onDrill(line.account_id)}>{line.code} · {line.name}</button></td><td>{line.type}</td><td>{line.debit_minor ? money(line.debit_minor) : "—"}</td><td>{money(line.credit_minor || line.amount_minor)}</td></tr>)}</tbody></table></div></section>; }
function CashFlowTable({ cash, money, headers }: { cash: CashFlow; money: (value: number) => string; headers: string[] }) { const sections = [cash.operating, cash.investing, cash.financing, cash.unclassified]; return <section className="card"><div className="table-scroll"><table><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{sections.flatMap((section) => [...section.lines.map((line) => <tr key={`${section.activity}-${line.journal_id}`}><td>{section.activity}</td><td>{line.occurred_at.slice(0, 10)}</td><td>{line.source_type}</td><td>{line.memo || "—"}</td><td>{money(line.amount_minor)}</td></tr>), <tr key={`${section.activity}-net`}><td><strong>{section.activity} NET</strong></td><td /><td /><td /><td><strong>{money(section.net_minor)}</strong></td></tr>])}</tbody></table></div></section>; }
